
* ExtentTree
** Operations
*** Split(X)
*** Group(A,B)
**** A and B inclusively mark contiguous range of Leaves
**** as such, there must be common Apex node
***** though the Apex as found might cover more than just our intended range, which we need to therefore adjust
**** Simplest complex case:
   X
  / \
 a   Y
    / \
   b   c

Group(a,b) finds apex X
but as found, this covers too much
fix would be: rearrange tree to be as so:

     X
    / \
   Y   c
  / \
 a   b

only Y must be free to do this
as X retains its place and its range
though its legs are manipulated

the original Y, if non-free, poses a problem
it would be a competing grouping
which is impossible in our scheme 

algo seems to be: find apex, rotate legs if poss
**** More complex:
       X
     /   \
   Y       Z
  / \     / \
 a   b   c   d

 Group(b,c) finds apex X
 now what?

 we /always/ need a new covering apex
 and if the number of leaves is odd, the subtree below the apex will be skew-whiff

 but in this case we only wish to cover 2 leaves
 and so the target state of a single apex covering no more and no less
 is our starting point

 we must want a subtree like this:
   N
  / \
 b   c
 
 also, we can start from X, a solid immovable point
 X can pop from the left to the right, or vice versa
 without overreaching, these are its two possible rejigs
 
 moving from left to right:
 the left leg must be a node (otherwise movement in this direction is pointless)
 the left leg node is dissolved
 the left grandchild becomes our immediate left child
 and the right grandchild is pushed under a new intermediate right child

 moving this left->right:
   X
  / \
 a   N
    / \
   b   c

 would only achieve this:
 X
  \
   N
  / \
 a   N
    / \
   b   c

 which only introduces a further indirection
 gains us no fidelity of range coverage whatsoever
**** Recap:
       X
     /   \
   N       N
  / \     / \
 a   b   c   d

 Group(b,c) finds apex X
 now what?

 we repeatedly perform ops
 until we are happy with the result

 in this case we would rotate L->R   /BUT HOW DO WE KNOW WHICH DIRECTION TO GO??/
   X
  / \
 a   N
    / \
   b   N
      / \
     c   d

 this gets us closer though we my not realise it
 the apex must be found again

 it makes sense that apex moves, or rather our pivot moves
 if it didn't, we'd be happy from the beginning!

 the current apex is our current problem
 it has its finger in the pie
 and we must rejig it to forget it and narrow away from it
   N
  / \
 a   X
    / \
   b   N
      / \
     c   d

   X
  / \
 b   N
    / \
   c   d

 we could reresolve the apex after every rotation: Apex(b,c)
 or is there some way to know if the apex has moved? and in which direction?

 we would repeatedly shift L->R with the same pivot
 until the happy moment when 'b', that is the recognisable left limit of the range
 is shifted over
 once this is done, we know that the new node we have synthesised to hold it
 is a better pivot for us, it is its inescapable apex

 it is also a possibility after each Shift(N)
 that our current pivot receives the left limit as its immediate left child
 in which case we are perfectly placed without any hopping over

 so, Shift(X) until we detect a either pushed under to the right, or newly immediately available to the left
 and in shifting we can't dissolve a fixed node

 this is a point: our apex may be perfect
 even with a mediated left limit
 tolerance of mediation allows fixed nodes to inhabit our new grouping

 from our pivot point, we need to know how many leaves in excess we have to the left
 and we must keep on shifting till this goes down to 0
 once at zero, we move to phase 2

 going down to zero is proof of perfection: we are the limit

 but alternatively we may detect the left limit itself being shifted
 which means we as apex are excessive
 we have found the perfect limit, but it is not us!
 we must move operations the synthesized child node as new apex

 or thirdly we may find our rotation impossible due to
 a fixing association, and we must error
 it is always TryShift(X) then...

 but at one of these terminals, we have our apex definitively for phase 2

 _PHASE 2_
 we are perfect to the left now
 but we still have excess to the right

   X
  / \
 b   N
    / \
   c   d
 
 now is time to repeatedly POP that excess away
 which is this simple rotation:

     N
    / \
   X   d
  / \
 b   c
 
 our left side is perfect
 but to do the above, we need to rotate from the node above us!

 the original apex might actually be fixed
 the apex covers more than what we want on its right side
 we know to aim at a more focused apex, the child of the current apex
 so the current apex can never be the answer, though we've just used
 it to skim off stuff 

 shifting never actually gets rid of stuff to the left
 the only way of doing this it through the final hop to a new node
 this is what skims off the excess to the left
 reducing to zero excess of course means we don't have to hop fortuituously
 but in this case we'd never shift at all
 we'd start from zero
 and know we just didn't have to shift

 if we do have excess, then we just keep on shifting until we detect
 that the level has been shifted
 therefore we don't have to keep tabs on the excess
 we just need to know /at first/ whether there is any excess at all
 simple!

 and if there is excess, on shifting, eventually we either fail or we detect
 the crucial limit passing through
 at which point we hop

 and reach Phase 2

 _PHASE 2 PART DEUX_
 Now we have this:
   X
  / \
 b   N
    / \
   c   d

 again as before, either we're perfect from the off
 or we have to repeatedly pop until we are

 popping is a leftwards shift, which involves dissolving nodes to the right

     X
    / \
   N   d
  / \   
 b   c 

 again, if detect the right limit going through, then we hop

 and recurse again


 Group(a,z) {
   (x, excessLeft, excessRight) = Apex(a,z)
    
   if excessLeft {
     x = Shift(x,a)
   }

   if excessRight {
     x = Unshift(x,z)
   }

   return apex
 }

 Shift(x,a) {
   rotate until a is on the right
   return new child node on right
 }

 Unshift(x,z) {
   rotate back until z is on the left
   return new left child node
 }

   
 /BIG IDEA/
 in finding the original apex
 we count the number of excess nodes

 if 0 then we know we're good
 otherwise we need to shift until 

 no - this only makes sense if we know the sizes of subtrees
 which we've not committed to currently

 we just know from Apex() what intermediate nodes there are of unknown overall weight
 could these intermediate nodes be cycled wholesale, not one by one????
**** Apex(a,z)
Apex(a,z) = FirstDivergentNode(LineageToRoot(a), LineageToRoot(z))

**** RECAP and: laziness?
we split Extents up into tokens
these tokens transparently rearrange themselves into a balanced binary tree
when we collect token under a larger node
we group their contiguous expanse
the old Split and Group ops

Split(Extent,Index): (Left,Right)

and were we going to make it mutable?
token splitting doesn't require us to go back necessarily (though we can imagine it might sometimes)
but grouping is definitively speculative

I feel like we've been here before but managed to climb out of it
previously we ended up with WeakRef-based ParentLinks, I know this much
which would mean parents know their children, and therefore we'd be creating new parents if they were immutable
I'm fairly sure mutability was the way we were going to go
nice quick rotations (imagine ints in an arena!)

but if we are to have mutations
we'll need a sealing step
simple as that
which complicates our basic APIs

Split and Group would have to be lazy then?
but if so, then we're going to construct quite big structures in memory

where do we seal in the parsing?
only at the end of the entire parsing
but this seems appropriate: parsing forms immutable structures that only point upwards (as with the parse tree)
and then on final sealing, we transcribe the structure into the ExtentTree
simple!

**** Laziness
still we want to Split and Group on Extents
and maybe there's chance to enforce constraints/accumulate helpful info

these ProtoExtents would have positive parent links
and in fact would still be split similarly
in fact maybe they could even be grouped similarly
what they completely lack is a means of diving downwards
but this is actually needed for rotating!
both lookup and rotation needs parent->child linkages

another idea (though dubious) would be to go whole hog immutability
and create new versions of the overall tree on each update
I don't like the wastefulness of this

and so our only alternative is to create a proto structure
with suspended splittings
or maybe the only bit that needs suspending is grouping!

Split can be done straight up without deferral
but balancing again requires troublesome rotation, so we can't balance from the off
and as we would then be stuck forming an inefficient linked list
it seems like we come back to a more specialised method of capture:
A simple queue of Ambits
but then with suspended groupings

so, a list of Splits and a list of Groups
though how would a Group refer to a Split?

unsure
but after a capture of all these Ambits
they can be articulated into a perfectly balanced binary tree
ready for grouping

or we could actually have a linked list...
in fact, to support immutability this is exactly what we'd need
a tail-first linked list

our consuming code just wants to use it as normal
we'd have an Extent and we want to split it up

this seems fine then:
the first splitting would be completely unbalanced

in fact the lazy sealing and grouping of the extents could be done by walking the Parse tree...
which would allow us to inject associations at that point too

So in phase 1, we accumalte ExtentOps: Split(Split? prev, int pos) | Group(Split from, Split to)

though these Groups... could they be made implicit?
as in, we don't need to create them specially: we just put the Splits in our ParseNodes
and then in walking our Parse nodes we can group our Extents

this soulds good to me

though previously we've favoured doing all this completely separately, as its own subsystem
this would still use the Group() operation, however it would be suspended into the Parse tree
best of both worlds, kinda
**** RECAP
as we tokenize, we create a Split(Split?, int) linked-list

and when we seal the parse tree, we walk this list to create a balanced Extent tree
which we then articulate by the Group operation

the Extent tree at this point optimises for searching out associations

the articulation itself happens by walking the Parse tree
but the Split->Extent conversion does not
as this would then allow us to skip tokens in our articulation
all would exist, but only our positive groupings would give us shape

Again:
1. accumulate Splits
2. on seal, convert these to Extents
   i. possibly balance this initial tree!
3. also on seal, walk the Parse tree top down, grouping he Extents and impressing associations

but why can't we just split out Extents?
simply because we want to be able to speculate with our tokens
which actually seems reasonable

but then we don't necessarily need a Reader...
as the point of the reader is to manage this speculation and to _commit_

if we ever wanted to explode the Parser/Lexer distinction (sounds fun) we'd definitely want this
plus a Split can be efficiently worked-backwards into an Extent tree, as it will be the same shape


NB
as soon as we split, we create something readable





*** Group(a,b):

TrimRight(x,b):

   X
  / \
 a   Y
    / \
   Z   d
  / \
 b  c

 we need to rotate nodes leftwards
 until we have everything snuggly captured by our left leg

 and to rotate, we go into the right leg
 we condense it down, extracting the nodes we ourselves care about
 possibly with structure intact
 in fact yes: we want not a queue of leaves, but of liberated fragments
 and then we go through this queue
 injecting it into the left leg

** Rotation ii
intention has been to pivot on a fixed point, to rotate below an apex
but ideally we'd have something recursive

we'd delve recursively, firstly down the one leg, and then down the other

delve and liberate, followed by injection of the accumulation

* Vectors and Extents
Leaves know their sizes directly
And Nodes can memoize on formation, with any changes bubbling up
But an Extent is not personally aware of its position within its container
It just knows its left and its right, and their sizes

Finding a position or range within the tree is therefore a matter of climbing the tree
and at each node choosing left or right, in a kind of binary search

But in our tests we are concerned initially with self-knowledge
ie extents should know their position and range
is this not something to be scanned?

For an entire subtree, we can deduce positions by enumerating all nodes

And for individual elements
we can find our position by working up the lineage

There are two modes, then:
- top-down report involving enumeration
- bottom-up self-recognition involving bubbling up through parents
* Readables and Sizes
sizes must be stored and accumulated separately from Readables, as otherwise
a size request against an entire document would summon up an entire Readable tree
covering the entire document.

Even if we stored Readables eagerly, this is an entire extra structure linking all fragments together
But Readables in their merging are actually consolidated passively,
plus we do want to have, at some distant time, an out-of-band consolidation mechanism
that puts all readables together

In short, using Readables as a base layer of aggregation might actually pay off
doing so would abstract away size aggregation and memoization: a plus

Readables must be aggregated eagerly, with sizes similarly eager.
We need to avoid recalculation.

Though when extents do change, their readables need to be updated in an upward bubbling



 

* Multipass parsing
We wanna occasionally parse forwards once to take in blocks of text
that can then be further parsed into shape

imagine a block of embedded Bash scripting
or a brace-delimited block of language statements

the more you parse ahead the less context you have for decision making, of course

and the only real advantage to using this mechanism for language elements
is a nice built-in curtailing of mistyped sections
one misplaced comma isn't going to derail the entire lot
ie there is value in it, even for this

parsing ahead would realise a node
then the question becomes, how to reduce this node in an idiomatic way?

given one node, we want to engage new parsers
(a parser could just be a Return of course)

formally presentable as a like-for-like translation between nodes
in S/R as a translation between sequences and equivalent new nodes
(mechanically as a matched stack operation)

no - more precisely we require mappings between matchable nodes and
new parsers: each parser becomes a reducer of - what?

in the simplest standard case, of a Readable
but other nodes could be reduced?

so each Parser is actually a Reducer of /things/

and reductions of things can be strung together

at the top level
we have a base reduction in place over Readable
if we have a readable, then this reduces/expands it to a more meaningful node
like the registration of a handler, in fact

how would changes propagate then?
and how would this all be set up to work with linguistic expansions also?

simply we'd start programming the reduce/expanders rather than the simple forward parsing
with matching on type of node
(potentially covering sequences also)

but how would this work with propagations?
a change to a frament would still reverberate up the parse tree
and the topmost part of the parse tree is now the reduction engine

recursive descent propagation would bubble up through
in-place Parsers, formed into a tree. Rejected potential Parsers
don't make it at all into this tree, and they only reappear if
their parent node is reset given certain damage

but above this, we have the matched reducers etc
which arrange parsers in series to form their results
closing over a combined upland of text/intermediate nodes

so Parsers, on exceptions, yield up to their parents
over their bound inputs

if the input is itself a node
the a change of this node
will invalidate reparsings of the same

damage to Readable would then invalidate the parsing of Readable->BlockNode,
which would then retrigger the BlockNode->StatementNodes reduction

in the case of Readables, damage is shaped, and effects only certain parsings
ie although text is monoidal, its bindings are not merged in toto
(therefore, bound text is not monoidal)
but it is monoidal! as long as bindings are scoped by offset and range

or is it more that Readables refer back into their own structure
and that parsings do in fact bind to particular readables...
behind the scenes these are in fact one big buffer (or a series of them)
but within the parsing they are treated as their own things,
which can be reduced, expanded etc.

A readable is reduced to a node tree by our top-level reduction
but this readable is extruded out into parts that can be bound to

A BlockNode is reduced to a StatementsNode
and we can bind to the upstream reduction
as the upstream isn't just the node but also its reduction

In recursive descent we don't bind to the overall input, but only to our accumulated part of it

------

damage propagation, how so?

a preparsed block would have within it many statements
and these statements would bind upmost to the Extents

though the first parsing of the block would itself parse on Extent
* Space
all parsers to transparently ingest leading space
according to the set of space chars

but the problem here is that as we speculatively try alternate parsings
we will repeatedly do the same space parsing
it needs to be done once and shared

which we achieve by absorbing space at the topmost level of parsing
and setting a flag in the context to say whether space has been sufficiently absorbed already

changing the space set resets this flag
and a successful response also
* Expectations and Options
How do they mix? If an expression is optional, then in particular parsing NOTHING is an option
but if there is something, and it is partially correct, then that should be our choice
if there is something, and it doesn't fit the optional parse
we should always try to parse it as the consecutive parsing
however this produces a OneOf disjunction:

the immediate text contains our optional element
OR the immediate text contains our consecutive element

these are two eventualities to assess and to order
** How it is now
we currently try to parse the optional
and if this is not fully successful
we are forced to capture this as an expectation
and then follow up with the successor

but it may be that the successor is very happy to absorb the immediate
and that expectations from the optional should be completely skipped past

OneOf gives us a mechanism for this
* Dec 24
The Steps /are not Parsers/ - because they don't necessarily return anything
so is parsing really business of the Runner?

we'd previously built up the parse stuff from SelectMany mappings

the proposal now is to do the same, except the SelectMany just projects different Steps out

previously we accumulated the parse structure by inscribing the SelectMany structure
which we then moulded together via a visitor - this worked

but now we want to take stuff out of the SelectManys

so the parse graph was basically the SelectManys, which themselves formed a tree
and each time a node is yielded, it 

yielding was brought in specifically so we could do the node association in the runner
instead of the SelectMany

except - the node association is done in the visitor, not in the SelectMany
and the Visitor relies on the parsing tree, which is just a projection of the SelectMany graph

so the Runner, if it was going to associate nodes, would be taking over from the Visitor
and that is exactly what we were expecting: the Runner would form the ParsingTree
which could then be visited and cleaned up etc as before

so the role of the Runner is reduced, albeit shifted still
if it can get the ParsingTree in place then all is good
and the ParsingTree is expected to be in the shape of the SelectManys

so the Steps, with which the Runner exclusively deals,
need to be in this shape as well - a tree of continuations and yields
given this structure, these can be mapped neatly into Parsings

Steps are more than Parsings, as some of them have no results, but are only steps forwards
the runner receives Steps, and condenses them then into Parsings - this is its job
the Steps then need to have the dependency strucure of the SelectManys, which the Parsings
require

Currently, Steps are transcribed just in series, with no indication of nesting
this must change!

We can either continue on the current path of balancing Enters and Yields
or we can make steps explicitly reference their parents

Enters and Yields are just transcriptions, but at the same time they form a nice serialized language layer
you can imagine these becoming some kind of byte code
though such byte code is itself just a projection of the _real_ structure
which is best represented by material links

so, moving back towards transcription of the SelectMany graph here
Steps would refer back to parents Steps
However: can we reliably create these within the fragments?
using LINQ will do it for us

Steps would have upstreams then
but wouldn't the Runner be able to track this itself?
a continuation that yields further steps surely asserts dependency between these steps

of course, as it reads off the stack, it cannot know this, as given the current storage
no information is retained of where Steps came from
but it could certainly capture this as it ran:
given a currently-held Step, all further Steps that come from it belong to it

SO!!!!
the current surmise is that the current Steps, as they are run by the Runner
do in fact form the same familiar tree
the Runner needs to accumulate upstreams as it runs continuations
(possibly with great nesting as now)
yet on Yield it won't re-ascend layer-by-layer
instead our current SelectManys, as they form the tree
do map Yields simply to Yields
and this collapses the layers
if we are to leave enough structure for the Runner to pick up
each intermediate Yield needs to be mapped into place
meaning a lot of Yields

unless a Yield held within it a reference to the originating Step of the layer
this would allow the intermediates to be elided

such a held ref would of course be a transcribing of the tree in the form of a link


----

from Match(A)
from Match(B)
select C

Match(A) -> Match(B) -> Return C

(Cont -> Return A) -> (Cont -> Return B) -> Return C

Cont -> (Cont -> Return A) -> (Cont -> Return B) -> Return C

----

But, as everything does run in series, we could track the tree
just with Enters, as this would establish a new frame, which would either Return
or whither away

the Runner, on encountering an Enter, would put this into its Context
(a stack of Contexts in fact) and pop it out when a Return was encountered

this would also mean we could get rid of Yields in favour of the original Returns

Yields' usefulness is all in how they allow us to close over crucial stuff
ie they create a space for bodging which our approach to the runner in fact can't tolerate

IN FACT
the only use of Yield currently is to _HIDE SELECTMANY_
and yet SelectMany is /exactly/ what we need to form the ParsingTree!

TODO:
- Get rid of Yield in favour of Return, which will allow us to track dependencies in the Runner with Enters/Returns


BUT: why are we supporting a SelectMany over a Return in the first place?
because we may have an opaque step we want to append to

we need access to the Return, just as the Runner needs access to the Return
the Yield is a mechanism for allowing this

the Yield in fact says: a stack frame is here being popped
but we have more to do now in the parent frame

THEREFORE: Yields just need to be handled properly
a Yield pop the current frame
and continues in its parent

if this continuation then Yields, it pops us out of the parent frame

Every ENTER either lines us up for a withering drought, or some positive Yields

----

We therefore com back to the matter of balancing Enters with Yields
every SelectMany can be an Enter, but if so, we also need to map the same number of Yields
and be certain about it
(but we can be certain, just by baking this into the SelectMany maps)

OR we can add a marker to the Yield to indicate the Enter we now want to go back to,
which would be a nice optimization

-----

RunSteps put necessary laziness around UDFs
but do they also commit us to doing yields at the end?
surely they do, as long as users have no access to Continues, but only to Returns and SelectManys

TODO: Enusre users can only access Return

-------

what is the actual point of Continues?

could we just have Enter((Enter|Yield)[])?

I think we could yes
the case in which an inner step would yield up its intermediate results would go like this:


Enter(A, [Enter(B, [Yield(B, [Enter(C), Yield(C)]]] 


Enter(A, [Enter(B, [])])




sudden inspirational thought:
instead of Yield
we want a Concat operator

Enter0
  Enter1
    Return

but the concat would require us to know what goes on

the case for the Yield is entirely in Return(1).SelectMany()
with some closing over the initial return opaquely in the background

/it can't be concat/ *because the following steps are always necessarily lazy, as the depend on input*

the truth is, this is the old monadic bind represented by SelectMany
so we could just have a Bind step

when we come across a Bind step, we know we must process the left side first
and then use the yielded result of the first in the second

Bind/Return

would we need Yield in this case? the answer is - no

would we need Enter? not convinced we would do
as the topmost Bind would be our Enter

-------

we work through Binds and Returns

Binds are pushed onto a stack but we also have a /current/ Step

-------

The parse tree...
is going to be in exactly the same shape as the Bind tree, isn't it?
maybe, except with dependencies and fragments captured

currently we have Bind -> Parsing -> Parsed which can surely be simplified down to two stages

-------------------------------

the folding of the parse tree now seems like it should be integrated with the Step tree
although the Step tree is certainly distinct from the ParsingTree
ie it is the input, whereas the ParsingTree represents intermediate results

but the folding of the ParsingTree does some things I dislike
notably the use of return values to create the shape of output Parseds

Bind/Return can determine this shape, rather than using such hackery?
returns feed into returns via binds

and a return in the left leg of a bind is subsidiary to the return into a right leg
but within each leg we have independent parts

is it the unwinding of the binds that do it?
as long as a return finds right legs to immediately unwind, then result can all be squished together

though - what if a bind does nothing but fanny about with a value,
which it then re-returns? we can't in this case rely on unwinding
we still need the folding in place then to cover this case
though immediate unwinding could compress stuff before we get to the folding

-------------------------

How would table-based parsing even work? or rather - how would it presented in the API?

currently potential parsings are built up sequentially and nestable
with table based continuations, all nestable sequences would also have contexts

Conjunction = Exp + '&' + Exp

the above little rule could be read as: given an Exp, try for a '&', and given this, try another Exp

also, the above rule could be specified monadically in query syntax as now
except, instead of sequentially exploring it, for every step we'd now what possible next steps there are
(with some kind of precedence) and there'd be an implicit OneOf between these possibilities

tables -> implicit OneOfs, no longer needing to be explicitly programmed, but just always there...

all steps would therefore need to be named
and, could steps have a simple concrete type, always returning subclasses of Node?
but - having nicely typed results lets us receive well-typed values from subparsings, to be arbitrarily processed

yer YACCs etc have a tangential limitation: actual processing code needs to be nested into the parsing
and is done ugly

currently we can tie arbitrary processings into the monads
which is pleasant - really we want to be able to do both
and to do the well-typed former, we need to refer to actual methods

static RunSteps fit the bill: there is one instance of each
and they can be cross-referenced and nested

but, given arbitrary lazy connecting code, how can we know the full step of steps and their concoctions
with which to populate the table? the answer: lazily

no sequence needs to be a concern until we get as far as testing for it, as part of a parent sequence
there's no spooky typeclass-style insinuation of parsers

as we proceed with our parsing, we therefore incrementally accumulate our table
but - LINQ allows arbitrary code all over the place, and never rules it out
if we had a separate syntax for sequences, then we could rule out the problematic opaque monads

it's basically a trie we want to construct
a single reading of the parsers lets us know what continuations are always available
but aren't these continuations always in a context?
if we gathered them /from the top/ all at once, then the position of each encounterable step
would be as clear as poss, but if we do the same lazily, only when needed,
we'd need to know how much of the preceding matching was actually needed

there'd always be a stacktrace or path from the top,
ie there'd be a designated root, which would always obviously be the entry parser

so...
for every encountered named RunStep, there'd be a stable path
and would such a path use the current bind tree for its structure?
obvs yes it would...

so the path would start of from ROOT
and there'd be unnamed steps from there with arbitrary code potentially

our approach is that the table is an optimisation
with the main thing gained by it the deduping of parsings

posing it as optimisation makes me think of it a further phase of rewriting
instead of as the fundamental mechanism at play

given a OneOf we replace it with a lookup table
but just lookup tables covering single steps?
this is almost what a OneOf is explicitly currently
a table of possible continuations which we fork between, albeit unfairly and in strict sequence
but instead of making the big choice up top
we find the optimum number of marginal steps, with disjunctions behind these

Root = A | B | C
A = X X
B = Y
C = X Z 

would become...

Root = X@0 | Y@B
0 = X@A | Z@C

------

but we couldn't do the above given arbitrary connecting code
the very first parsings in a RunStep aren't however affected by this
as arbitrary code hangs only on the result of the first step

if there was some way to be sure of independence of steps
then we could be sure of their equality in different sites
and we can specify such with a special sequence operator - but not with the usual LINQ from-in

the input structure for this optimisation would be the bind/return tree
but we'd need more info about each step - they'd need to be made more transparent with palpable matchable types

-----

if tables are then just an optimising rewriting
shouldn't our current naive processing work fine though inefficiently?

there was some expressivity missing before...

given (A | B) & C

we were getting stuck in parsing (A | B)
with the & not being followed
to follow the &, ParseConjunction needs to attempt (Exp)

------

but the current structure of the parsers isnn't great...
we delegate downwards quite arbitrarily
through a succession of contextualy-irrelevant parsers
and without OneOfs structuring these

ideally, we'd be able to hang a succession of relations off ParseExp

Conjunction = Exp '&' Exp
Disjunction = Exp '|' Exp
Addition    = Exp '+' Exp

but we've expressly done this to avoid the cost of reparsing via a top-level OneOf
if we could do this, given we have a vague plan for making it efficient,
then our parsers could be much more attractively laid-out

********************************************************
TODO change our Parsers to use a top-level OneOf
********************************************************

but - the problem with using the top-level OneOf
is really one of recursion

e.g.

Exp = Disjunction
Disjunction = Exp '|' Exp

will endlessly loop

presumably it wouldn't if we were expanding preexisting parsings
actually unsure how it could do anything but recurse
it's kind of necessitated by the rules themselves, no matter how they're read

even an implicit mark or deduction of the appearance if the root wouldn't lead anywhere better
as the problem still stands: how do we evaluate this actual recursion?

the path isn't totally recursive: there are many legitimate pathways that would yield a result
but in their midst we have Bottom
which we could cope with given fair exploration of disjunctive paths
as it is true that a parsing could /legitimately/ have nested expressions to an arbitrary extent

given an Exp, it's always possible to append '|' to it to make it an uncertain disjunction
this omnipresently-possible continuation aligns with ever-available recursion through the rules

if this makes perfect sense, why does it cause such an issue for our sequential processing?

because we would greedily plunge into it, and never find its full depth
it's a trap for our greediness
so - how can we be less greedy?


NB the below is unavoidably recursive:
Exp = Disjunction
Disjunction = Exp '|' Exp

but if Exp had a disjunction in it, then it wouldn't be
and would only be problematic if eagerly explored withoout fairness

so how would fairness be implemented?
threads with independent stacks
threads would form a tree, branching on each disjunctions
on every step we'd alternate between threads

---

but this complete fairness would rob us of programmability
some rules we do want to consider first before others

eg simple terminals should be matched before conjunctions
but if this was all we did, to short-circuit the looping,
then we wouldn't be able to parse 1 & 2
as we'd only parse 1, and then stop

but with fair exploration

Num would ultimately fail, given the excess after its initial success

Exp & Exp
would succeed

there's also the possibility here of caching results
Num would succeed at first, and this initial success could be cached to be picked up by Exp & Exp


Num = /[0-9]+/
Exp = Num | Add
Add = Exp '+' Exp


symbols would be linked to by concrete parsings

/[0-9]+/ is a concrete parsing, a Matcher, and is available at the top level

/[0-9]+/ -> Num 
 
Num -> Exp

Exp /[\+]/ Exp

---------

Exp is the root

Num is tried, alongside Add
Add tries for Exp, which tries for Num|Add, which tries for Exp, etc

if there were caching of /attempts/ to parse certain symbols at each point, then
as Add tries again to parse Exp,
we would find Exp in the cache, albeit as yet incomplete
and we could add continuation steps to the fulfilment of that parsing

ie don't start again what we've already begun

would the context actually be the same? yes, it would
but would we have threads in place here? threads are our only mechanism for fairness
so if we want fairness, we must have them

threads would share the same cache
but their continuations, registered against a particular parsing,
would run on the original thread

such caching would stop duplicate parsing, but with some overhead
every time a symbol were attempted given a particular input context
we would try to secure a cache entry
(not just a check but a registration, as _everything_ should be cached)

caches would live only for the duration of one single context

and the only way in which such caches would be shared would be via Fork()
which in fact /wouldn't/ fork the cache

what else? how would we key the cache?
each step would need an id
a preallocated table
that gets cleared between steps rather than reformed

and which steps? ALL OF THEM - not just named

so this means that /all steps need a name/
but - this only really matters for steps that can recurse
which can only be named steps in the first place!

though - if steps are named, then they will have single instances
meaning: we don't need to key on their name, but on their ref

---

given a context (or immediately forked context)
we store cached cells of parsings from this point
this means left-recursiveness is supported, with the left point being the immediate context that stores the cache

---

can we cache based on actual parser instance? we can with how we currently use it
but if we were to use a step as a template we've had it

better caching on key, if available
though... actually not sure we even need to do that

how does the cacheing interact with the implicit absorption of space?
if space was definitely/defiantly an extra interpolated step
then we would be covered: disjunctive OneOfs would do their space parsing step
and then only after this would the caching kick in

if we didn't interpolate a step, what would occur?
the space would be reparsed? potentially, but in practice no
as the space should be covered by the OneOf

an issue is that the context gets mutated (and presumably its cache reset)
if there is parsable space

---

what we're actually caching are Left legs of binds
reaching into these left legs clearly involves churning the context

or - does it?
maybe the cache just holds the right parts of binds
given a result from a cached left leg
then we feed it to various continuations
which continuations will have contexts and the inverted continuations

so the cache will get checked, as now, on every processing of a step
but it only makes sense to do so within a bind?

if we cache on the processing of the subject step,
and it is just a return
then it will be of no use

continuations can only come from within the processing of a Bind
on processing a Bind, if the left leg is /known/ then, instead of processing it,
we can instead register our continuation

the crucial thing is clearing the shared cache on /traversing/ the Bind
ie all is bind specific

how does this interact with space again?
the bind that finds the cacheable should already have parsed preceding space
and other binds will do the same
but - I'm not sure we can cover these space parsings in our cache
as the outermost bind will capture the space
while the innermost contains the cacheable leg

unless Binds were somehow transparent as to their left legs
but - we can't cache the topmost bind
as there's a tower of uncapturable continuations in its intermediate layers
unless these intermediate continuations were also captured in the cache cell
and the stack of continuations is in fact capturable in the context

---

so we encounter a cacheable step
as part of a bind, in the left leg of a bind
we put the continuation of our current bind in the cache cell
and in the bind stack we put a frame that multiplies out to pursue all the cached continuations
in fact, the continuations in a cache cell are /very similar if not exactly identical/ to the bind continuations in the bind stack

transitive bind lefts would be covered if we only hopped threads on continuations
ie we would for free work through nested bind lefts as part of normal eager processing

so, as part of encountering a bind, we sense its left leg is cacheable
and instead of pushing StartedLeft onto the stack
no actually - we can /lean on/ the preexisting StartedLeft
each StartedLeft has a mutable list of continuations
which gets shared with the appropriate cache cell

---

we don't just cover nested recursions, we also need to cover sibling paths that begin the same
which means the processing of a cacheable step might in fact have completed
when we want to summon it
this means the cache cell has two modes (possibly encapsulated within it)
if we're active, then we just register a 'callback' within it and wait for it to complete (or not)
but if its already complete, then we should continue with our current processing
but - the cell may have produced multiple results, or none
so - a complete cell has not just one outcome, but an array of them



















































































































































































































































































