
* ExtentTree
** Operations
*** Split(X)
*** Group(A,B)
**** A and B inclusively mark contiguous range of Leaves
**** as such, there must be common Apex node
***** though the Apex as found might cover more than just our intended range, which we need to therefore adjust
**** Simplest complex case:
   X
  / \
 a   Y
    / \
   b   c

Group(a,b) finds apex X
but as found, this covers too much
fix would be: rearrange tree to be as so:

     X
    / \
   Y   c
  / \
 a   b

only Y must be free to do this
as X retains its place and its range
though its legs are manipulated

the original Y, if non-free, poses a problem
it would be a competing grouping
which is impossible in our scheme 

algo seems to be: find apex, rotate legs if poss
**** More complex:
       X
     /   \
   Y       Z
  / \     / \
 a   b   c   d

 Group(b,c) finds apex X
 now what?

 we /always/ need a new covering apex
 and if the number of leaves is odd, the subtree below the apex will be skew-whiff

 but in this case we only wish to cover 2 leaves
 and so the target state of a single apex covering no more and no less
 is our starting point

 we must want a subtree like this:
   N
  / \
 b   c
 
 also, we can start from X, a solid immovable point
 X can pop from the left to the right, or vice versa
 without overreaching, these are its two possible rejigs
 
 moving from left to right:
 the left leg must be a node (otherwise movement in this direction is pointless)
 the left leg node is dissolved
 the left grandchild becomes our immediate left child
 and the right grandchild is pushed under a new intermediate right child

 moving this left->right:
   X
  / \
 a   N
    / \
   b   c

 would only achieve this:
 X
  \
   N
  / \
 a   N
    / \
   b   c

 which only introduces a further indirection
 gains us no fidelity of range coverage whatsoever
**** Recap:
       X
     /   \
   N       N
  / \     / \
 a   b   c   d

 Group(b,c) finds apex X
 now what?

 we repeatedly perform ops
 until we are happy with the result

 in this case we would rotate L->R   /BUT HOW DO WE KNOW WHICH DIRECTION TO GO??/
   X
  / \
 a   N
    / \
   b   N
      / \
     c   d

 this gets us closer though we my not realise it
 the apex must be found again

 it makes sense that apex moves, or rather our pivot moves
 if it didn't, we'd be happy from the beginning!

 the current apex is our current problem
 it has its finger in the pie
 and we must rejig it to forget it and narrow away from it
   N
  / \
 a   X
    / \
   b   N
      / \
     c   d

   X
  / \
 b   N
    / \
   c   d

 we could reresolve the apex after every rotation: Apex(b,c)
 or is there some way to know if the apex has moved? and in which direction?

 we would repeatedly shift L->R with the same pivot
 until the happy moment when 'b', that is the recognisable left limit of the range
 is shifted over
 once this is done, we know that the new node we have synthesised to hold it
 is a better pivot for us, it is its inescapable apex

 it is also a possibility after each Shift(N)
 that our current pivot receives the left limit as its immediate left child
 in which case we are perfectly placed without any hopping over

 so, Shift(X) until we detect a either pushed under to the right, or newly immediately available to the left
 and in shifting we can't dissolve a fixed node

 this is a point: our apex may be perfect
 even with a mediated left limit
 tolerance of mediation allows fixed nodes to inhabit our new grouping

 from our pivot point, we need to know how many leaves in excess we have to the left
 and we must keep on shifting till this goes down to 0
 once at zero, we move to phase 2

 going down to zero is proof of perfection: we are the limit

 but alternatively we may detect the left limit itself being shifted
 which means we as apex are excessive
 we have found the perfect limit, but it is not us!
 we must move operations the synthesized child node as new apex

 or thirdly we may find our rotation impossible due to
 a fixing association, and we must error
 it is always TryShift(X) then...

 but at one of these terminals, we have our apex definitively for phase 2

 _PHASE 2_
 we are perfect to the left now
 but we still have excess to the right

   X
  / \
 b   N
    / \
   c   d
 
 now is time to repeatedly POP that excess away
 which is this simple rotation:

     N
    / \
   X   d
  / \
 b   c
 
 our left side is perfect
 but to do the above, we need to rotate from the node above us!

 the original apex might actually be fixed
 the apex covers more than what we want on its right side
 we know to aim at a more focused apex, the child of the current apex
 so the current apex can never be the answer, though we've just used
 it to skim off stuff 

 shifting never actually gets rid of stuff to the left
 the only way of doing this it through the final hop to a new node
 this is what skims off the excess to the left
 reducing to zero excess of course means we don't have to hop fortuituously
 but in this case we'd never shift at all
 we'd start from zero
 and know we just didn't have to shift

 if we do have excess, then we just keep on shifting until we detect
 that the level has been shifted
 therefore we don't have to keep tabs on the excess
 we just need to know /at first/ whether there is any excess at all
 simple!

 and if there is excess, on shifting, eventually we either fail or we detect
 the crucial limit passing through
 at which point we hop

 and reach Phase 2

 _PHASE 2 PART DEUX_
 Now we have this:
   X
  / \
 b   N
    / \
   c   d

 again as before, either we're perfect from the off
 or we have to repeatedly pop until we are

 popping is a leftwards shift, which involves dissolving nodes to the right

     X
    / \
   N   d
  / \   
 b   c 

 again, if detect the right limit going through, then we hop

 and recurse again


 Group(a,z) {
   (x, excessLeft, excessRight) = Apex(a,z)
    
   if excessLeft {
     x = Shift(x,a)
   }

   if excessRight {
     x = Unshift(x,z)
   }

   return apex
 }

 Shift(x,a) {
   rotate until a is on the right
   return new child node on right
 }

 Unshift(x,z) {
   rotate back until z is on the left
   return new left child node
 }

   
 /BIG IDEA/
 in finding the original apex
 we count the number of excess nodes

 if 0 then we know we're good
 otherwise we need to shift until 

 no - this only makes sense if we know the sizes of subtrees
 which we've not committed to currently

 we just know from Apex() what intermediate nodes there are of unknown overall weight
 could these intermediate nodes be cycled wholesale, not one by one????
**** Apex(a,z)
Apex(a,z) = FirstDivergentNode(LineageToRoot(a), LineageToRoot(z))

**** RECAP and: laziness?
we split Extents up into tokens
these tokens transparently rearrange themselves into a balanced binary tree
when we collect token under a larger node
we group their contiguous expanse
the old Split and Group ops

Split(Extent,Index): (Left,Right)

and were we going to make it mutable?
token splitting doesn't require us to go back necessarily (though we can imagine it might sometimes)
but grouping is definitively speculative

I feel like we've been here before but managed to climb out of it
previously we ended up with WeakRef-based ParentLinks, I know this much
which would mean parents know their children, and therefore we'd be creating new parents if they were immutable
I'm fairly sure mutability was the way we were going to go
nice quick rotations (imagine ints in an arena!)

but if we are to have mutations
we'll need a sealing step
simple as that
which complicates our basic APIs

Split and Group would have to be lazy then?
but if so, then we're going to construct quite big structures in memory

where do we seal in the parsing?
only at the end of the entire parsing
but this seems appropriate: parsing forms immutable structures that only point upwards (as with the parse tree)
and then on final sealing, we transcribe the structure into the ExtentTree
simple!

**** Laziness
still we want to Split and Group on Extents
and maybe there's chance to enforce constraints/accumulate helpful info

these ProtoExtents would have positive parent links
and in fact would still be split similarly
in fact maybe they could even be grouped similarly
what they completely lack is a means of diving downwards
but this is actually needed for rotating!
both lookup and rotation needs parent->child linkages

another idea (though dubious) would be to go whole hog immutability
and create new versions of the overall tree on each update
I don't like the wastefulness of this

and so our only alternative is to create a proto structure
with suspended splittings
or maybe the only bit that needs suspending is grouping!

Split can be done straight up without deferral
but balancing again requires troublesome rotation, so we can't balance from the off
and as we would then be stuck forming an inefficient linked list
it seems like we come back to a more specialised method of capture:
A simple queue of Ambits
but then with suspended groupings

so, a list of Splits and a list of Groups
though how would a Group refer to a Split?

unsure
but after a capture of all these Ambits
they can be articulated into a perfectly balanced binary tree
ready for grouping

or we could actually have a linked list...
in fact, to support immutability this is exactly what we'd need
a tail-first linked list

our consuming code just wants to use it as normal
we'd have an Extent and we want to split it up

this seems fine then:
the first splitting would be completely unbalanced

in fact the lazy sealing and grouping of the extents could be done by walking the Parse tree...
which would allow us to inject associations at that point too

So in phase 1, we accumalte ExtentOps: Split(Split? prev, int pos) | Group(Split from, Split to)

though these Groups... could they be made implicit?
as in, we don't need to create them specially: we just put the Splits in our ParseNodes
and then in walking our Parse nodes we can group our Extents

this soulds good to me

though previously we've favoured doing all this completely separately, as its own subsystem
this would still use the Group() operation, however it would be suspended into the Parse tree
best of both worlds, kinda
**** RECAP
as we tokenize, we create a Split(Split?, int) linked-list

and when we seal the parse tree, we walk this list to create a balanced Extent tree
which we then articulate by the Group operation

the Extent tree at this point optimises for searching out associations

the articulation itself happens by walking the Parse tree
but the Split->Extent conversion does not
as this would then allow us to skip tokens in our articulation
all would exist, but only our positive groupings would give us shape

Again:
1. accumulate Splits
2. on seal, convert these to Extents
   i. possibly balance this initial tree!
3. also on seal, walk the Parse tree top down, grouping he Extents and impressing associations

but why can't we just split out Extents?
simply because we want to be able to speculate with our tokens
which actually seems reasonable

but then we don't necessarily need a Reader...
as the point of the reader is to manage this speculation and to _commit_

if we ever wanted to explode the Parser/Lexer distinction (sounds fun) we'd definitely want this
plus a Split can be efficiently worked-backwards into an Extent tree, as it will be the same shape


NB
as soon as we split, we create something readable





*** Group(a,b):

TrimRight(x,b):

   X
  / \
 a   Y
    / \
   Z   d
  / \
 b  c

 we need to rotate nodes leftwards
 until we have everything snuggly captured by our left leg

 and to rotate, we go into the right leg
 we condense it down, extracting the nodes we ourselves care about
 possibly with structure intact
 in fact yes: we want not a queue of leaves, but of liberated fragments
 and then we go through this queue
 injecting it into the left leg

** Rotation ii
intention has been to pivot on a fixed point, to rotate below an apex
but ideally we'd have something recursive

we'd delve recursively, firstly down the one leg, and then down the other

delve and liberate, followed by injection of the accumulation

* Vectors and Extents
Leaves know their sizes directly
And Nodes can memoize on formation, with any changes bubbling up
But an Extent is not personally aware of its position within its container
It just knows its left and its right, and their sizes

Finding a position or range within the tree is therefore a matter of climbing the tree
and at each node choosing left or right, in a kind of binary search

But in our tests we are concerned initially with self-knowledge
ie extents should know their position and range
is this not something to be scanned?

For an entire subtree, we can deduce positions by enumerating all nodes

And for individual elements
we can find our position by working up the lineage

There are two modes, then:
- top-down report involving enumeration
- bottom-up self-recognition involving bubbling up through parents
* Readables and Sizes
sizes must be stored and accumulated separately from Readables, as otherwise
a size request against an entire document would summon up an entire Readable tree
covering the entire document.

Even if we stored Readables eagerly, this is an entire extra structure linking all fragments together
But Readables in their merging are actually consolidated passively,
plus we do want to have, at some distant time, an out-of-band consolidation mechanism
that puts all readables together

In short, using Readables as a base layer of aggregation might actually pay off
doing so would abstract away size aggregation and memoization: a plus

Readables must be aggregated eagerly, with sizes similarly eager.
We need to avoid recalculation.

Though when extents do change, their readables need to be updated in an upward bubbling



 

* Multipass parsing
We wanna occasionally parse forwards once to take in blocks of text
that can then be further parsed into shape

imagine a block of embedded Bash scripting
or a brace-delimited block of language statements

the more you parse ahead the less context you have for decision making, of course

and the only real advantage to using this mechanism for language elements
is a nice built-in curtailing of mistyped sections
one misplaced comma isn't going to derail the entire lot
ie there is value in it, even for this

parsing ahead would realise a node
then the question becomes, how to reduce this node in an idiomatic way?

given one node, we want to engage new parsers
(a parser could just be a Return of course)

formally presentable as a like-for-like translation between nodes
in S/R as a translation between sequences and equivalent new nodes
(mechanically as a matched stack operation)

no - more precisely we require mappings between matchable nodes and
new parsers: each parser becomes a reducer of - what?

in the simplest standard case, of a Readable
but other nodes could be reduced?

so each Parser is actually a Reducer of /things/

and reductions of things can be strung together

at the top level
we have a base reduction in place over Readable
if we have a readable, then this reduces/expands it to a more meaningful node
like the registration of a handler, in fact

how would changes propagate then?
and how would this all be set up to work with linguistic expansions also?

simply we'd start programming the reduce/expanders rather than the simple forward parsing
with matching on type of node
(potentially covering sequences also)

but how would this work with propagations?
a change to a frament would still reverberate up the parse tree
and the topmost part of the parse tree is now the reduction engine

recursive descent propagation would bubble up through
in-place Parsers, formed into a tree. Rejected potential Parsers
don't make it at all into this tree, and they only reappear if
their parent node is reset given certain damage

but above this, we have the matched reducers etc
which arrange parsers in series to form their results
closing over a combined upland of text/intermediate nodes

so Parsers, on exceptions, yield up to their parents
over their bound inputs

if the input is itself a node
the a change of this node
will invalidate reparsings of the same

damage to Readable would then invalidate the parsing of Readable->BlockNode,
which would then retrigger the BlockNode->StatementNodes reduction

in the case of Readables, damage is shaped, and effects only certain parsings
ie although text is monoidal, its bindings are not merged in toto
(therefore, bound text is not monoidal)
but it is monoidal! as long as bindings are scoped by offset and range

or is it more that Readables refer back into their own structure
and that parsings do in fact bind to particular readables...
behind the scenes these are in fact one big buffer (or a series of them)
but within the parsing they are treated as their own things,
which can be reduced, expanded etc.

A readable is reduced to a node tree by our top-level reduction
but this readable is extruded out into parts that can be bound to

A BlockNode is reduced to a StatementsNode
and we can bind to the upstream reduction
as the upstream isn't just the node but also its reduction

In recursive descent we don't bind to the overall input, but only to our accumulated part of it

------

damage propagation, how so?

a preparsed block would have within it many statements
and these statements would bind upmost to the Extents

though the first parsing of the block would itself parse on Extent
* Space
all parsers to transparently ingest leading space
according to the set of space chars

but the problem here is that as we speculatively try alternate parsings
we will repeatedly do the same space parsing
it needs to be done once and shared

which we achieve by absorbing space at the topmost level of parsing
and setting a flag in the context to say whether space has been sufficiently absorbed already

changing the space set resets this flag
and a successful response also
* Expectations and Options
How do they mix? If an expression is optional, then in particular parsing NOTHING is an option
but if there is something, and it is partially correct, then that should be our choice
if there is something, and it doesn't fit the optional parse
we should always try to parse it as the consecutive parsing
however this produces a OneOf disjunction:

the immediate text contains our optional element
OR the immediate text contains our consecutive element

these are two eventualities to assess and to order
** How it is now
we currently try to parse the optional
and if this is not fully successful
we are forced to capture this as an expectation
and then follow up with the successor

but it may be that the successor is very happy to absorb the immediate
and that expectations from the optional should be completely skipped past

OneOf gives us a mechanism for this
* TODO Dec 24
The Steps /are not Parsers/ - because they don't necessarily return anything
so is parsing really business of the Runner?

we'd previously built up the parse stuff from SelectMany mappings

the proposal now is to do the same, except the SelectMany just projects different Steps out

previously we accumulated the parse structure by inscribing the SelectMany structure
which we then moulded together via a visitor - this worked

but now we want to take stuff out of the SelectManys

so the parse graph was basically the SelectManys, which themselves formed a tree
and each time a node is yielded, it 

yielding was brought in specifically so we could do the node association in the runner
instead of the SelectMany

except - the node association is done in the visitor, not in the SelectMany
and the Visitor relies on the parsing tree, which is just a projection of the SelectMany graph

so the Runner, if it was going to associate nodes, would be taking over from the Visitor
and that is exactly what we were expecting: the Runner would form the ParsingTree
which could then be visited and cleaned up etc as before

so the role of the Runner is reduced, albeit shifted still
if it can get the ParsingTree in place then all is good
and the ParsingTree is expected to be in the shape of the SelectManys

so the Steps, with which the Runner exclusively deals,
need to be in this shape as well - a tree of continuations and yields
given this structure, these can be mapped neatly into Parsings

Steps are more than Parsings, as some of them have no results, but are only steps forwards
the runner receives Steps, and condenses them then into Parsings - this is its job
the Steps then need to have the dependency strucure of the SelectManys, which the Parsings
require

Currently, Steps are transcribed just in series, with no indication of nesting
this must change!

We can either continue on the current path of balancing Enters and Yields
or we can make steps explicitly reference their parents

Enters and Yields are just transcriptions, but at the same time they form a nice serialized language layer
you can imagine these becoming some kind of byte code
though such byte code is itself just a projection of the _real_ structure
which is best represented by material links

so, moving back towards transcription of the SelectMany graph here
Steps would refer back to parents Steps
However: can we reliably create these within the fragments?
using LINQ will do it for us

Steps would have upstreams then
but wouldn't the Runner be able to track this itself?
a continuation that yields further steps surely asserts dependency between these steps

of course, as it reads off the stack, it cannot know this, as given the current storage
no information is retained of where Steps came from
but it could certainly capture this as it ran:
given a currently-held Step, all further Steps that come from it belong to it

SO!!!!
the current surmise is that the current Steps, as they are run by the Runner
do in fact form the same familiar tree
the Runner needs to accumulate upstreams as it runs continuations
(possibly with great nesting as now)
yet on Yield it won't re-ascend layer-by-layer
instead our current SelectManys, as they form the tree
do map Yields simply to Yields
and this collapses the layers
if we are to leave enough structure for the Runner to pick up
each intermediate Yield needs to be mapped into place
meaning a lot of Yields

unless a Yield held within it a reference to the originating Step of the layer
this would allow the intermediates to be elided

such a held ref would of course be a transcribing of the tree in the form of a link


----

from Match(A)
from Match(B)
select C

Match(A) -> Match(B) -> Return C

(Cont -> Return A) -> (Cont -> Return B) -> Return C

Cont -> (Cont -> Return A) -> (Cont -> Return B) -> Return C

----

But, as everything does run in series, we could track the tree
just with Enters, as this would establish a new frame, which would either Return
or whither away

the Runner, on encountering an Enter, would put this into its Context
(a stack of Contexts in fact) and pop it out when a Return was encountered

this would also mean we could get rid of Yields in favour of the original Returns

Yields' usefulness is all in how they allow us to close over crucial stuff
ie they create a space for bodging which our approach to the runner in fact can't tolerate

IN FACT
the only use of Yield currently is to _HIDE SELECTMANY_
and yet SelectMany is /exactly/ what we need to form the ParsingTree!

TODO:
- Get rid of Yield in favour of Return, which will allow us to track dependencies in the Runner with Enters/Returns


BUT: why are we supporting a SelectMany over a Return in the first place?
because we may have an opaque step we want to append to

we need access to the Return, just as the Runner needs access to the Return
the Yield is a mechanism for allowing this

the Yield in fact says: a stack frame is here being popped
but we have more to do now in the parent frame

THEREFORE: Yields just need to be handled properly
a Yield pop the current frame
and continues in its parent

if this continuation then Yields, it pops us out of the parent frame

Every ENTER either lines us up for a withering drought, or some positive Yields

----

We therefore com back to the matter of balancing Enters with Yields
every SelectMany can be an Enter, but if so, we also need to map the same number of Yields
and be certain about it
(but we can be certain, just by baking this into the SelectMany maps)

OR we can add a marker to the Yield to indicate the Enter we now want to go back to,
which would be a nice optimization

-----

RunSteps put necessary laziness around UDFs
but do they also commit us to doing yields at the end?
surely they do, as long as users have no access to Continues, but only to Returns and SelectManys

TODO: Enusre users can only access Return

-------

what is the actual point of Continues?

could we just have Enter((Enter|Yield)[])?

I think we could yes
the case in which an inner step would yield up its intermediate results would go like this:


Enter(A, [Enter(B, [Yield(B, [Enter(C), Yield(C)]]] 


Enter(A, [Enter(B, [])])




sudden inspirational thought:
instead of Yield
we want a Concat operator

Enter0
  Enter1
    Return

but the concat would require us to know what goes on

the case for the Yield is entirely in Return(1).SelectMany()
with some closing over the initial return opaquely in the background

/it can't be concat/ *because the following steps are always necessarily lazy, as the depend on input*

the truth is, this is the old monadic bind represented by SelectMany
so we could just have a Bind step

when we come across a Bind step, we know we must process the left side first
and then use the yielded result of the first in the second

Bind/Return

would we need Yield in this case? the answer is - no

would we need Enter? not convinced we would do
as the topmost Bind would be our Enter

-------

we work through Binds and Returns

Binds are pushed onto a stack but we also have a /current/ Step

-------

The parse tree...
is going to be in exactly the same shape as the Bind tree, isn't it?
maybe, except with dependencies and fragments captured

currently we have Bind -> Parsing -> Parsed which can surely be simplified down to two stages

-------------------------------

the folding of the parse tree now seems like it should be integrated with the Step tree
although the Step tree is certainly distinct from the ParsingTree
ie it is the input, whereas the ParsingTree represents intermediate results

but the folding of the ParsingTree does some things I dislike
notably the use of return values to create the shape of output Parseds

Bind/Return can determine this shape, rather than using such hackery?
returns feed into returns via binds

and a return in the left leg of a bind is subsidiary to the return into a right leg
but within each leg we have independent parts

is it the unwinding of the binds that do it?
as long as a return finds right legs to immediately unwind, then result can all be squished together

though - what if a bind does nothing but fanny about with a value,
which it then re-returns? we can't in this case rely on unwinding
we still need the folding in place then to cover this case
though immediate unwinding could compress stuff before we get to the folding

-------------------------

How would table-based parsing even work? or rather - how would it presented in the API?

currently potential parsings are built up sequentially and nestable
with table based continuations, all nestable sequences would also have contexts

Conjunction = Exp + '&' + Exp

the above little rule could be read as: given an Exp, try for a '&', and given this, try another Exp

also, the above rule could be specified monadically in query syntax as now
except, instead of sequentially exploring it, for every step we'd now what possible next steps there are
(with some kind of precedence) and there'd be an implicit OneOf between these possibilities

tables -> implicit OneOfs, no longer needing to be explicitly programmed, but just always there...

all steps would therefore need to be named
and, could steps have a simple concrete type, always returning subclasses of Node?
but - having nicely typed results lets us receive well-typed values from subparsings, to be arbitrarily processed

yer YACCs etc have a tangential limitation: actual processing code needs to be nested into the parsing
and is done ugly

currently we can tie arbitrary processings into the monads
which is pleasant - really we want to be able to do both
and to do the well-typed former, we need to refer to actual methods

static RunSteps fit the bill: there is one instance of each
and they can be cross-referenced and nested

but, given arbitrary lazy connecting code, how can we know the full step of steps and their concoctions
with which to populate the table? the answer: lazily

no sequence needs to be a concern until we get as far as testing for it, as part of a parent sequence
there's no spooky typeclass-style insinuation of parsers

as we proceed with our parsing, we therefore incrementally accumulate our table
but - LINQ allows arbitrary code all over the place, and never rules it out
if we had a separate syntax for sequences, then we could rule out the problematic opaque monads

it's basically a trie we want to construct
a single reading of the parsers lets us know what continuations are always available
but aren't these continuations always in a context?
if we gathered them /from the top/ all at once, then the position of each encounterable step
would be as clear as poss, but if we do the same lazily, only when needed,
we'd need to know how much of the preceding matching was actually needed

there'd always be a stacktrace or path from the top,
ie there'd be a designated root, which would always obviously be the entry parser

so...
for every encountered named RunStep, there'd be a stable path
and would such a path use the current bind tree for its structure?
obvs yes it would...

so the path would start of from ROOT
and there'd be unnamed steps from there with arbitrary code potentially

our approach is that the table is an optimisation
with the main thing gained by it the deduping of parsings

posing it as optimisation makes me think of it a further phase of rewriting
instead of as the fundamental mechanism at play

given a OneOf we replace it with a lookup table
but just lookup tables covering single steps?
this is almost what a OneOf is explicitly currently
a table of possible continuations which we fork between, albeit unfairly and in strict sequence
but instead of making the big choice up top
we find the optimum number of marginal steps, with disjunctions behind these

Root = A | B | C
A = X X
B = Y
C = X Z 

would become...

Root = X@0 | Y@B
0 = X@A | Z@C

------

but we couldn't do the above given arbitrary connecting code
the very first parsings in a RunStep aren't however affected by this
as arbitrary code hangs only on the result of the first step

if there was some way to be sure of independence of steps
then we could be sure of their equality in different sites
and we can specify such with a special sequence operator - but not with the usual LINQ from-in

the input structure for this optimisation would be the bind/return tree
but we'd need more info about each step - they'd need to be made more transparent with palpable matchable types

-----

if tables are then just an optimising rewriting
shouldn't our current naive processing work fine though inefficiently?

there was some expressivity missing before...

given (A | B) & C

we were getting stuck in parsing (A | B)
with the & not being followed
to follow the &, ParseConjunction needs to attempt (Exp)

------

but the current structure of the parsers isnn't great...
we delegate downwards quite arbitrarily
through a succession of contextualy-irrelevant parsers
and without OneOfs structuring these

ideally, we'd be able to hang a succession of relations off ParseExp

Conjunction = Exp '&' Exp
Disjunction = Exp '|' Exp
Addition    = Exp '+' Exp

but we've expressly done this to avoid the cost of reparsing via a top-level OneOf
if we could do this, given we have a vague plan for making it efficient,
then our parsers could be much more attractively laid-out

********************************************************
TODO change our Parsers to use a top-level OneOf
********************************************************

but - the problem with using the top-level OneOf
is really one of recursion

e.g.

Exp = Disjunction
Disjunction = Exp '|' Exp

will endlessly loop

presumably it wouldn't if we were expanding preexisting parsings
actually unsure how it could do anything but recurse
it's kind of necessitated by the rules themselves, no matter how they're read

even an implicit mark or deduction of the appearance if the root wouldn't lead anywhere better
as the problem still stands: how do we evaluate this actual recursion?

the path isn't totally recursive: there are many legitimate pathways that would yield a result
but in their midst we have Bottom
which we could cope with given fair exploration of disjunctive paths
as it is true that a parsing could /legitimately/ have nested expressions to an arbitrary extent

given an Exp, it's always possible to append '|' to it to make it an uncertain disjunction
this omnipresently-possible continuation aligns with ever-available recursion through the rules

if this makes perfect sense, why does it cause such an issue for our sequential processing?

because we would greedily plunge into it, and never find its full depth
it's a trap for our greediness
so - how can we be less greedy?


NB the below is unavoidably recursive:
Exp = Disjunction
Disjunction = Exp '|' Exp

but if Exp had a disjunction in it, then it wouldn't be
and would only be problematic if eagerly explored withoout fairness

so how would fairness be implemented?
threads with independent stacks
threads would form a tree, branching on each disjunctions
on every step we'd alternate between threads

---

but this complete fairness would rob us of programmability
some rules we do want to consider first before others

eg simple terminals should be matched before conjunctions
but if this was all we did, to short-circuit the looping,
then we wouldn't be able to parse 1 & 2
as we'd only parse 1, and then stop

but with fair exploration

Num would ultimately fail, given the excess after its initial success

Exp & Exp
would succeed

there's also the possibility here of caching results
Num would succeed at first, and this initial success could be cached to be picked up by Exp & Exp


Num = /[0-9]+/
Exp = Num | Add
Add = Exp '+' Exp


symbols would be linked to by concrete parsings

/[0-9]+/ is a concrete parsing, a Matcher, and is available at the top level

/[0-9]+/ -> Num 
 
Num -> Exp

Exp /[\+]/ Exp

---------

Exp is the root

Num is tried, alongside Add
Add tries for Exp, which tries for Num|Add, which tries for Exp, etc

if there were caching of /attempts/ to parse certain symbols at each point, then
as Add tries again to parse Exp,
we would find Exp in the cache, albeit as yet incomplete
and we could add continuation steps to the fulfilment of that parsing

ie don't start again what we've already begun

would the context actually be the same? yes, it would
but would we have threads in place here? threads are our only mechanism for fairness
so if we want fairness, we must have them

threads would share the same cache
but their continuations, registered against a particular parsing,
would run on the original thread

such caching would stop duplicate parsing, but with some overhead
every time a symbol were attempted given a particular input context
we would try to secure a cache entry
(not just a check but a registration, as _everything_ should be cached)

caches would live only for the duration of one single context

and the only way in which such caches would be shared would be via Fork()
which in fact /wouldn't/ fork the cache

what else? how would we key the cache?
each step would need an id
a preallocated table
that gets cleared between steps rather than reformed

and which steps? ALL OF THEM - not just named

so this means that /all steps need a name/
but - this only really matters for steps that can recurse
which can only be named steps in the first place!

though - if steps are named, then they will have single instances
meaning: we don't need to key on their name, but on their ref

---

given a context (or immediately forked context)
we store cached cells of parsings from this point
this means left-recursiveness is supported, with the left point being the immediate context that stores the cache

---

can we cache based on actual parser instance? we can with how we currently use it
but if we were to use a step as a template we've had it

better caching on key, if available
though... actually not sure we even need to do that

how does the cacheing interact with the implicit absorption of space?
if space was definitely/defiantly an extra interpolated step
then we would be covered: disjunctive OneOfs would do their space parsing step
and then only after this would the caching kick in

if we didn't interpolate a step, what would occur?
the space would be reparsed? potentially, but in practice no
as the space should be covered by the OneOf

an issue is that the context gets mutated (and presumably its cache reset)
if there is parsable space

---

what we're actually caching are Left legs of binds
reaching into these left legs clearly involves churning the context

or - does it?
maybe the cache just holds the right parts of binds
given a result from a cached left leg
then we feed it to various continuations
which continuations will have contexts and the inverted continuations

so the cache will get checked, as now, on every processing of a step
but it only makes sense to do so within a bind?

if we cache on the processing of the subject step,
and it is just a return
then it will be of no use

continuations can only come from within the processing of a Bind
on processing a Bind, if the left leg is /known/ then, instead of processing it,
we can instead register our continuation

the crucial thing is clearing the shared cache on /traversing/ the Bind
ie all is bind specific

how does this interact with space again?
the bind that finds the cacheable should already have parsed preceding space
and other binds will do the same
but - I'm not sure we can cover these space parsings in our cache
as the outermost bind will capture the space
while the innermost contains the cacheable leg

unless Binds were somehow transparent as to their left legs
but - we can't cache the topmost bind
as there's a tower of uncapturable continuations in its intermediate layers
unless these intermediate continuations were also captured in the cache cell
and the stack of continuations is in fact capturable in the context

---

so we encounter a cacheable step
as part of a bind, in the left leg of a bind
we put the continuation of our current bind in the cache cell
and in the bind stack we put a frame that multiplies out to pursue all the cached continuations
in fact, the continuations in a cache cell are /very similar if not exactly identical/ to the bind continuations in the bind stack

transitive bind lefts would be covered if we only hopped threads on continuations
ie we would for free work through nested bind lefts as part of normal eager processing

so, as part of encountering a bind, we sense its left leg is cacheable
and instead of pushing StartedLeft onto the stack
no actually - we can /lean on/ the preexisting StartedLeft
each StartedLeft has a mutable list of continuations
which gets shared with the appropriate cache cell

---

we don't just cover nested recursions, we also need to cover sibling paths that begin the same
which means the processing of a cacheable step might in fact have completed
when we want to summon it
this means the cache cell has two modes (possibly encapsulated within it)
if we're active, then we just register a 'callback' within it and wait for it to complete (or not)
but if its already complete, then we should continue with our current processing
but - the cell may have produced multiple results, or none
so - a complete cell has not just one outcome, but an array of them

---

Current bug:

existence of alternate leg that gets explored before expected conjunction parsing breaks things
it must be having some effect, despite supposedly being isolated...

thought before was that the ParseContext must not be being forked, but...
other possible contamination is via shared cache cell

problem comes when ParseConjunction is encountereed within ParseEquality within ParseExpression

what should be happening:

Exp should create a cell
Exp/Equality should create a cell
Exp/Equality/Conjunction should create a cell

Exp/Conjunction should find preexisting cell

---

What should happen:

As we start on ParseExpression
a cell is put in the bind frame
meaning, when we eventually finish parsing the expression,
we'll refind the bind frame
and populate the topmost cell

but for a top-level ParseExpression,
nothing else will ever encounter this!
as we are inevitably the sole parsing at the top

But if we're OneOf at the top, then this isn't true

because the expression will only be complete when the /entire lot is complete/

so we start on the Exp
and because Exp is cacheable,
we put a continuation cell in the cache, and also in the bind frame

when within parsing the Exp
we happily parse a Ref, which fulfils the Exp
so - after parsing the Ref(A), we should unwind back to the B(Exp)
and in doing so, we should find a continuation within the receiving BindFrame

which, given our immediate success, shouldn't yet bear any trace of continuations

however - as Ref(A) is insufficient for parsing success
(despite happily filling the step cache)
we are then thrown back on continuing through thr top level OneOf

we now find ParseEquality, and its nested ParseExp
which should immediately succeed via the preserved StepCache
though the next attempt to parse '=' will fail
throwing us onto the next option

ParseConjunction finds the same immediate success
there is an Exp in the StepCache
and now we try parsing '&' etc

the first time we should find a cell in place is in the second leg
under ParseEquality; though we do of course encounter it on completion of ParseRef also

what's actually happening is that Exp/Ref(A) is succeeding, but it isn't populating the cell
due to an oversight

however, Exp/Equals/Ref /is/ populating it (second time lucky)

and as such, it /should/ be found by Exp/Conj/Exp 

Exp/Equals/Exp/Equals is finding it
Exp/Equals/Exp/Conjunction is finding it
(good good!)

a fascinating issue emerges:
Ref(A) firstly populates the StepCache
but soon we find better (or, at least, alternative) successful parsings

such alternatives shouldn't overwrite previous parsings
but complement them

how is this possible though?
if we're parsing an Exp, we might find multiple possible routes to an Exp

/so - a ContinuationCell should merge results/

however: if we've already continued from a cell in its partial completion
then that original encounter needs to pick up these new options
like every thread needs a live cursor

/to recap/
- our top-level parsing of a Ref is not getting put in the cache
- cell.Next should be a List of possible continuations
  - also each consumer should be added to cell, so that they catch up with new findings


---

how can Exp/Ref
populate the Exp cell??

/it should already be doing!/
because the thread that parses Ref
should be unwinding out of the OneOf
and setting it

interesting point:
when we first encounter R('A')
there's no Starting in the stack with a cell to be populated...

though there are plenty of frames with cacheable binds
but they are all in Completing state (ie executing rhs)

almost like our expectation that
everything gets returned up into a waiting Left
is quite wrong...

the Match(A) evidently returns first into a Right
in fact - all novelty will be returned into a Right

a Left is basically a delegation to a lower level
the actual registering of a result is done by Right

which suggests unwinding into a Right should populate the cell

---

there's a problem in specifying precedence

ParseConjunction is first
which populates A&B quite happily, though ending in failure

TBC...

---

Bloody precedence again
somehow I managed to sidestep it previously

but here's an idea:
implicit precedence based on position in OneOf
the alternative is some explicit barrier mechanism (not nice oh no)

such a mechanism would stop us exploring branches under some conditions

Exp/Disj
would find Exp/Ref, expanded into Exp/Conj

basically the kitchen sink is thrown at the task,
token-by-token, until we get results

and so A&B is firstly found
except B is expanded out into B|C

by ParseDisjunction
though we're under ParseConjunction at this point

Conjunction, being higher up the OneOf
should implicitly get a more local precedence
meaning, if we recurse within this, we shouldn't then loop into higher-precedence parsings

this does mean that caching requires precedence to be used as part of the key
but if we do this, then cache sites with slightly difference precedences won't hit
this /might/ work if we hit given lower precedence in the cache

Low precedence would come from being higher up the OneOf

though we start off in the highest precedence
ie we stand on nothing and are desperate for /anything/
and so we'll parse using any rule

but then we start in ExpressionBlock
which should greedily again parse anything
yet this is part of the OneOf list too
and is quite separate in its requirements from operators

so... this says we can't just implicitly use OneOf order
the only other option is to have explicit barriers

HOWEVER we can make things nicer
with syntactical cleverness
some kind of fluent syntax 
would be appropriate

*TODO*
- RunSteps to have optional precedence

---

PROBLEM OF CACHEING WITH PRECEDENCE

previously, given a position and a parser, we could easily reacquaint ourselves of the outcome via the StepCache

however, now we also have precedence alongside position
is this a crucial difference-making parameter? unsure

yes, it is: ParseExpression within one ambit of precedence will parse differently than from within another
but, though it therefore needs to form part of the cache key,
it doesn't need to be evaluated expecting identity

in fact the precedence barriers need to be around the connecting ops eg '&' and ''|'
which allows us to use simple cache keys



just had the thought:
the ordering of parser rules within OneOfs
/could have an effect/
if recursion worked a little bit more favourably


why can't precedence be done on the rule rather than on the matching of an operator?
as soon as we started parsing an addition, say, our precedence would straight away be quite low

and we'd straight away try to parse the leading expression
and suddenly we'd be in a low precedence, and so the ParseExpression we were wanting would be constrained

really the barrier is on the forward parsing of the operator
YACC evidently doesn't store precedence against the recursive token reference

the cache is only a matter on current step
any small movement makes it a matter of the past

but in the current way,
we're relying on actual concrete parsings to be done within arbitrary contexts opportunistically
which is fine only as long as these contexts are transparent

if Name was top of the OneOf
then this would quickly populate Exp
but all paths are attempted!

so we wouldn't just have Name
but also Name|Name
and Name|Name|Name
basically anything that the text supports is to be tried out

---

really I want the precedences to be against the overall parser
instead of having to interject them within the parser
this would allow entire rules to peremptorily skipped

this comes a cropper when we summon from the cache, as we're now in a new context

how can precedence not propagate?
it's the only way for different zones to touch and interact
and if it propagates, it must work its way transitively throug nested parsers

eg ParseAddition would parse further Exps as its left and rights, but only /weakly/

A + B / C

Add would parse its RHS comparatively weakly
ie with low precedence

but if the precedence was against the entire rule
it would also affect the LHS

---

what about unary minus?


---

precedence is a thing because we're implicitly matcing rules
well, actually unlike YACC we're not...

it's just we're relying on nested matches of Exp to cover everything
so how do we say within a rule that we want to constrain a recursion

---

and do we want to cache with precedence in the key
I think we do, actually
but it should seldom be used
if precedence only comes in on matching of operators

---

problem again of capturing precedence in cached parsings
though - it's not really a problem as 
within a particular location we never actually have different precedences in play
the problem just is that precedences are currently thrown away

is this a problem?
actually again, by chance, no...

---

Precedences work by bubbling up through binds
this allows them to lassoo larger ares of processing above

but - LINQ translation puts Match('&').With(precedence: 1)
in the lazy right leg of a bind
which is inevitable as it must follow something before
and within itself there will be a more local Left/Right that it does affect
but not one with sufficient reach to cover all until our return

and in fact that step of query syntax is potentially arbitrarily determined
by previous steps, and so can't stand pristinely and immovable
until the last moment of processing

so precedence can only be known on encountering it - not before

the issue is that continuations are joined on at the root, seemingly, rather than delegated down

from a in A
from b in B
from c in C
from d in D
...

(A, (B, (C, D)))

if we put precedence on B
we want it to last till end of D
/which it should do normally/
as we do a big unwind at the end

so - it should work as is

but in reality, the precedence isn't bubbling sufficiently...

because somewhere under conjunction
we're within the right leg
but this is to be expected!

---

there's a possibility here that the tree of binds isn't actually like:

(A, (B, (C, D)))

but sometimes like:

((A, B), (C, D))

or even at its worst:

(((A, B), C), D)

which would lessen B's reach
and we wouldn't have recourse to any magic to fix it
there needs to be some supporting structure to hang stuff off

on SelectMany, we get the following results:
A
(A, B)
((A, B), C)

which is exactly our worst-case scenario!!!

to get our desired structure,
SelectMany would have to cunningly reconstruct its LHS

A
(A, >B)
(A, >(B, >C))

in fact doing the above seems like by far the best option
for scalability

otherwise large programs are just going to be an unsurmountable stack
of binds to traverse up top

---

are there any benefits to SelectMany simply wrapping?
(instead of relying on magic)

something about bubbling propagation of Infos?
we'll inevitably find out, as this path is unavoidable
we gotta take it for efficiency

---

BUT BUT BUT

we can't recreate steps because we rely on their identities for caching

so, after all we do have to build up this mass of calcified coral around them
or - we mutate them
or we optimise them somewhere else, with the same effect

if we can restructure them up top we should be able to do the same /anywhere/

so... how can we???


(A, >(B, >(C, >D)))

from

(((A, >B), >C), >D)

SelectMany always builds out the above, where its in force

---

idea: we could reform 'transparent' binds, but not RunSteps which have to stay as they are

another problem: binds don't just have single right-hand-sides
they multiply out

but - we could pre-invert steps as we execute them

(((A, >B), >C), >D)

the mechanism would greedily root out the LHS of binds

(((A, >B), >C), >D)

a stack of delvings

(((A, >B), >C), >D) []
((A, >B), >C)       [>D]
(A, >B)             [>C, >D]
A                   [>B, >C, >D]

isn't this what we are doing already with the BindStack? it surely is

---

so if B introduces a precedence
how long should it last till?

till the top of the stack, obvs!
basically until a return occurs

*for the duration of the thread*

if we're within a OneOf, when we join back into the parent, that's when the precedence is dropped

obviously contexts aren't shared between disjunctions
and do disjunctions ever rejoin the superior context?
I'm not sure if they actually do

Exp = Multiply | Add | Value
Blah = Exp + ',' + Exp

in the Blah rule above each Exp is an encapsulated disjunction
but there should be precedences in play outside the ambits of the actual sub-parsings
so it really is just a case of knowing when a subparsing /ends/

is it on the end of the OneOf?
which is the join we're after surely

---

somehow precedence is leaking across legs

it does seem that OneOf isn't the perfect fork/join site
as, if it was then every binds results would be a sufficient disjunction to do the same
or is there a qualitative difference between a single and multiple results?

maybe instead precedences aggregate nicely when there is only a single result
but, precedences aren't just informational: they're a contextual marker to be carried around

it is true isn't it: precedence only matters for the /current parsing/
as soon we hop to the next (via a Bind) then our precedence is reset

the issue is being able to set precedence in ParseConjunction etc
on the operator
yet its effect should be felt on ParseExpression following it
a simple (and obvious) solution would be to put the precedence on the overall rule, as with YACC

but the problem now is that the leftmost Exp then is deformed by this constraint
really the constraint is around ('&' Exp)
not the LHS at all

obviously we can explicitly put this grouping in place
though it will add ugly weight to user-level code

we're seeking an elegant shortcut
which is certainly possible - as we can read how it should work intuitively

we want a setting of precedence /across binds/ ie sticky precedence
which is sticky until... some conventional point that matches expectations and usage

---

what should happen if we set precedences within a OneOf?

naturally, precedence should only attach to (and suffuse) a single conglomerate step

again, we can't do this with our rules
because we are relying on them to populate cached entries

How about: a look behind operator to opt out of precedence and spacing on a leading parsing
this is going to complicate stuff again, the inverse of the explicit opt-in originally discussed

---

But even if we do put the precedence at the rule level
and use some means to opt-out
the natural thing to do is to /not opt out/
which will create a big hard-to-understand mess

ie UX-wise this is a bad idea

it should instead work without having to explicitly opt out

(Exp + '&' + Exp)

in the above, putting the constraint on the leading Exp indeed makes no sense
*is the simple solution then just putting the precedence constraint around the RHS???**

except, as we know, we don't have a top level bind here structured that way
instead we have a big stack of nested binds
and even if we delve through the layers of left legs
how do we distinguish the ParseExp invocation?

is it just we delve until we hit a RunStep?

but this again seems too particularly suited to our case of binary operator parsing

---

in YACC, the leading Exp in a rule isn't bothered by the precedence attribute
it seems to simply be attached to a particular point in the rule
and only actually evaluated on contention
like a little tag

whereas for us, we don't contend because we equinaminously try everything
ie we don't reduce up top, thereby multiplying out our work considerably

again, the obvious solution is to explicitly specify a context around the operator and its subsequent Exp

----------

*IDEA IDEA IDEA*

how about we don't eagerly parse in the case of recursion

for instance, we start from parsing Exp
and when we meet Exp again
we don't actually delve into it

/so... precedence on the RunStep doesn't actually cause any problems whatsoever!/

as long as we have no expectations of precedence propagating through implicitly cached parsings

this would work in the case of recursion, as we have with Ex[]

---

what if, though, we're not recursive
ie: Number + '++'
for incrementation

encountering Number here 
before Number itself
would delve into it and populate it in the cache

how about: /we never delve into RunSteps/ on the left
instead we always register our interest 
and push a top level frame to investigate them 
without our current precedence

but this only amounts to /precedence not propagating on the left/

which is a familiar point to make...

so, when we process a bind, we always have a preset precedence
which may stop us exploring the bind

two situations: either the precedence is offered by the bind itself as a guard against evaluating its right leg
or the precedence is already in place, in which case it guards the left leg

this means that the leftmost parsing is magical

---

however, if the binds are structured as below (as they in fact are):

(((A, >B), >C), >D)

then the RunStep's only point of access is before >D - ie far too late
unless we start delegating the precedence-setting downwards
(defo no good)

however, if the responsibility is on the >B evaluation (ie on the Right of (A, >B))
then what's the problem?

it gets set there and continues till the end of the containing OneOf

ALTERNATELY we could revert when we get to end of RunStep
when we set precedence, we find latest RunStep (poss by maintaining a separate stack - or could search for bind of correct type)
or - RunSteps could /always/ reset precedence to original

so changes to precedence within a RunStep
would be squished

THIS IS A GOOD IDEA ********

and would make OneOf much less magic

---

precedence precedence precedence

how do we reset precedence here:

A = [1, B|C, 3]

well, every cell of the list is its own bounded expression
we therefore need some 

but do we need to explicitly encapsulate such parsing?

it's almost like, by default, precedence shouldn't be in play
but has to be opted into

a Barrier operator and a mutator to change the context around arbitrary steps would I think work

but... wouldn't we come a cropper in exactly the same way as now?
we'd again need some way of resetting the power of the parsing

---

YACC does precedence by trying to match multiple rules at a time, and then having nudge points
we also try to match multiple rules, though we do it exhaustively 
and we pare down the possibilities by testing the consistency of parsings

ie a oarsing has to make sense in itself, rather than just being locally preferred in one place
everything that's gathered has to work with the rules
whereas YACC takes an imperative nudge at pain points

somehow then we need to specify how operators will be gathered

precedences should only propogate over certain operators
and '(' forms therefore a natural barrier, unless we give it explicit precedence

instead of covering the entire ParseExpression then
we'd somehow leach into it from the side
not unlike the StepCache in fact

---

another thought: not all binary expressions are expanded by delving, sometimes we also
yield back to a top-level expression
ie the expand scenario
but in this case we will resume with the original precedence

---

so, Barrier and WithPrecedence
will give us all the necessary tools
but ugly, unless combined with BinaryExp parser
and even then... we'd have to put explicit resets in

we've been here before obvs

so does Yacc not need resets?
no, because it doesn't do propagation
instead it dedupes its disjunctions
and knows where the marginal choices are made
instead of us lomping along with our cache

we could compact down the tree, except for the lack of transparency of some of our intermediate binds
even if we marked some as transparent and traversed them as such
there's always the possibility of arbitrary code interpolated

so we're always liable to make something uncompactable given the freedom we offer

I can of course imagine a table based parser, put in place of the current exploratory one
but this can be saved for later - if we even want such a thing

so... let's do the Barrier, WithPrecedence and ResetPrecedence thing, balefully

---

is there no way we can just have adversarial tags?

no, because our disjuncts are too separate

what if binds were 'absorbed' into OneOfs?
left legs could be grouped

!!!!!!!!!!!!!!
the choice affected by precedence is between /parsing into/
and yielding back and expanding /from the top/

we have an operator next to be parsed, say a '|' pipe
and the question is, do we parse it into the current binary expression

or do we say we are too weak to handle it, and therefore we need delegate to the more powerful upper parsing?

--------

IDEA

we can avoid having to manually reset parsing strength if precedence is only in effect
on the immediate step: ie parsing a '(' should reset precedence naturally

but we put the precedence rule on the parsing of the operator
which however only really propagates through the subsequent parsing

even YACC must propagate, as once an op has been parsed, it must travel to be applied to the subsequent op parse

or is it on the rule itself?
basically, recursion inwards is affected

so on the rule itself
we don't enter the rule unless we have a certain parsing strength
*SO: barrier on the containing rule*

but then we have the problem of capturing the strength 
in the LHS parsing

the barrier should be on the overall rule
but the actual strength only expressed on the specific recursion

the parsing power is specified on the point of recursion
the barrier is specified on the overall rule

what would happen with resetting given brackets?
the only way of avoiding a manual reset is to reset on parsing

wait, so how does YACC propagate then
not explicitly, is the answer

WithStrength(5)
Require

ParseAddition.RequireStrength(3).WithStrength(3)

WithMaxStrength()

---------

Further probs: Prop parses, but then to parse further Props, what can we do?
we need delimited list then?

no, we want auto-expansion
like, after parsing an expression
we should try parsing again
until there's literally nothing more to do

Expand should benefit from the StepCache making Expressions available
but - the StepCache clears on success
so the original Expression will be dropped

Exp then Exp again, but via the cache only
maybe it can be available via a OneOf
ie a path in which we haven't moved on
yet the cache is populated

so - if we've not succeeded,
then we can continue as we were
but the lack of success is only a special one:
if we have more to parse

AUTO-EXPANSION
if we are at the end of the road and have nothing else available (and yet more to parse)
can we try the root rule once more
with the StepCache in place?

I suppose, the cursor would go back to the beginning
(with the cache retained)
and the rule evaluated one last time

eg Prop would then find an Expression available which it could work with

problem: it isn't always the root rule we wish to expand here
in a full scenario ParseExpression wouldn't be at root
instead we'd have ParseDocument or similar, much less liable to expansion

and even if we wished to explicitly expand, how would we do it?

---

ParseProp takes an expression and a ref, (itself becoming an expression)
this should then feed into a further ParseProp hanging off the expression cell

we need cells to provide endless continuations
each time a parsing of an expression is successfully done in the first position, it should be cast forwards via the cell

*HELLO!*
we need to fix the continuations: instead of having a simple Next prop serving as complete/pending
we need to support multiple completions
and each continuation, as it attaches to a cell, should both get up to date by continuing existing completions,
and also register itself to continue on further ones

with this in place, ParseProp should expand the root Exp by itself

---

but when we first come up against ParseExpression
there's a base strength to the parsing, a minimum threshold
as well as the local strength of the current rule

the rule that appends itself to the continuation 
only consumes emissions weaker than its filter

ParseAdd starts with top strength
its lhs has a diminished strength of 50
which means it will only consume continuations with a strength of 50 or below

its rhs also has a strength of 50, which propagates into and conditions its parsing

---

if we parse something with a strength, that means we can filter continuations based on it
but there must be another way of prescribing strength on an instigated parsing
otherwise a weak ParseAdd would cache a weak ParseExp unsuitable for stronger parsings

the cache could key on strength
and then filter out unsuitables
meaning weaker parsings could use emissions of stronger parsings

but this only works if the strong parsing is done first to seed the cache
but - in recursions this is exactly what occurs
the root of the recursion will be stronger, and will be the original

in the case of another non-root parsing being needed
the appearance of the parsing strength in the cache key covers us

---

the lhs of ParseAdd is modified to limit to a strength of 50
yet the rule itself is parsed with a strength of 1000

the lhs is therefore parsed with a strength of 1000
but continuations only fire through if strength is equal to or below 50

---

but if the strength is part of the key, it needs nevertheless to be ignored in the summoning of it,
or rather, we should always store only the strongest parsing in the cache
if we need a stronger one, we need to start again, and emplace the new stronger one in place of the weaker

this though is inelegant, with the threat of duplicate processing

in the case most in focus, it works fine, as start from a high pitch of strength, and then access this recursively with potential filtering

but, without this recursing, imagine instead the parsing of a lhs number by two separate rules
with different strengths

one rule parses with a strength of 10, another with 100
if the rule with a strength of 100 is done first, it will fill the cache with filterable emissions and all is fine
but if the weaker goes first, then the cached emissions will be insufficient for the 100

---

it's almost like we need a more eager folding of processing (in order to guarantee strong parsings first)
so, instead of parsing in arbitrary orders,
OneOf could always order by strength (though - this removes an important point of programmability)

amongst other things, this loops back slightly to OneOf giving rules implicit strengths based on their positions

`Number | Addition | Multiplication` would disallow Addition recursing through Multiplication

though we can problematise it as so:

`Block | Number | Addition | Multiplication`

here Block would have to explicitly reset precedence on its recursive Exp
whereas each rule in the oneof would be implicitly given a strength

---

back to the eager folding
(so that we know how strongly we have to parse each time)

given a OneOf, we find the strongest leg, and use this as our effective parsing strength
but then each continuation on this parsing checks its own strength, ie filters the upstream emissions

---

the strength of a rule then can't apply to its LHS
instead it applies to its continuation (or rather its covering bind)

this LHS - at which level is it?
the filter should apply as close as possible - actually /on/ the continuation

so we need two strengths: one the upper bound of strength for the current step(s)
and the other the requisite strength of the rule

but the upper bound of strength should be particular to the parsable, not to the whole shebang
ie there is a maximum strength needed for each cacheable parsable
which can be netted by exploring the tree, and only delving into the cacheable rule only when we've gone through all LHS steps

a two-phase running of the tree: first we walk through all steps
and enqueue continuations (instead of delving immediately if no cell is in place)
and only when this phase has completed do we then delve into the cacheables

how will we know we have completed the first phase?
because we will have no more frames to execute in the current context

which means frames need to be in a context? each time there's a OneOf
then we create a new context
with its own stack of frames to be completed
a StepContext effectively, shared between disjunctions - just like the current StepCache

this StepFrames will be worked through until empty; and when empty we will then process the accumulated
StepContinuations (ie the StepCache)

in processing the StepContinuations,
new Frames will be populated, to be explored

---

does the above amount to a premature folding?
yes it does
each possibility is explored to a minimal depth
and then deduplicated

---

each time we have a stack to execute
we therefore have a short-term StepFrameStack 
which we work through

could we just use the central frame stack?
but with a superior frame task that is - kick off continuations?
I think we indeed could
so every step adds a Contination step
which holds a ref to the StepCache
and 'progresses' the continuations when we get to it

therefore, no special StepFrameStack needed

---

record ProcessContinations(StepCache) : IStep

---

thought from the shower: ref counting on continuation dictionary
on final release, all funcs are fired

what's the positive effect of this?
it allows us to run continuations with maximum initial strength to avoid parsing impossibilities
but in any case we need to also filter strengths

it's not just continuations that are held back, but the cacheable itself
so the current parsing absorbs all immediates and works forwards
only up to the next concrete steps

on release of the continuation dictionary,
then we parse the concrete steps
this means the dictionary needs to store more than just the continuations
it has the concrete steps as available keys

these concrete steps don't need input
they are invariably independent legs
whose results get receied and processed by continuation binds

that's exactly what makes them sharable - they are free-standing

---

this though points towards them always being LHS steps
well... the continuations can be differently situated withing the tree
as long as they have the same effective ParseContext

any change to the parsecontext needs to invalidate the cache
the cache could even be keyed by text position, version and step
which would allow a more lattice-like processing
but - would this actually be used much? no

---

so - when we encounter a concrete step,
we register a continuation and we fizzle out
this removes our claim on the continuation dictionary

but this only works if registrations are done up front,
which I don't believe they will be
given a OneOf we therefore need to preload all steps
so that all next steps exist on the frame stack from the off
and as part of being on the frame stack, they will refer to the Cont dict

what is the thing that refers to the dict?
what else but a Fibre?

a OneOf forks a Fibre - isn't this Fibre then just the RunContext?

and forking must double the claims on all continuables

so every time we fork, we must walk all our encountered continuables
and increase counts on each

---

a return then (maybe only briefly)
to discuss the alternative to ref counting
which is pushing of a continuation phase to be explored only after 
all threads have faltered

really as well we would have multiple continuations in play
as each new continuable was encountered
or rather - a new phase of exploration would begin,
parsing up to the point where there is nothing to parse
and then we would recourse to our assembled continuables

this came a cropper previously over quibbles around where and when to begin
each such exploratory phase

each phase would start and end with a continuable
from the off we have a phase in place (because the top level _must_ be concrete?)

but phases end as soon as the ParseContext proceeds

---

Cursor has its movements
whenever it moves it releases its hold on the ContinuationContext

Cursor therefore owns continuations
and its two actions mediate its fluctuating ownership
Cursor.Fork retains the continuation context, and duplicates references
Cursor.Move releases it, and creates a pristine new one

this is novel: nesting of continuations within the Cursor
with clearer modifying actions

---

the Cursor would then hold references to a contdict
which would be released on movement

when all cursors leave a position
then the continuations should be enqueued

---

couple of questions:
- what about fairness of evaluation? up to this point we've basically been exploring leg by leg, depth first
  with this mechanism in place, we suddenly leap from one thread to a series of others
  but with a big discrepency between a penultimate and a final non-continuing thread
  as only in the latter case will we be suddenly able to leap sideways
  maybe we shouldn't leap

  ie - on movement forwards if a ContinuationDict has been freed 
  we could enqueue its further exploration rather than immediately diving into it

  in fact, it does seem like a phase should be fully explored before we start going after continuations

  in the beginning of a phase we therefore enqueue a clearing of continuations
  (and these continuations don't have to be in any order or grouping)

  every step accumulates continuations as above, but they accumulate in the per-phase simple collection of continuations
  which will itself only get actioned at the withering of all paths within a phase

  so a continuable encountered several steps on will get evaluated alongside an immediately encountered continuable
  and the threads will go out of sync, which is surely a bad thing for locality and its efficiencies

  but going out of sync is inevitable - the tendrils need to reach out into varying spaces
- what about accumulating space usage?
  the very first step in a document will of course feature a disjunction
  we only know we can shed other disjuncts either when we have proceeded sufficiently with one leg
  or we know other legs go nowhere

  fairness is our friend, and allows us to clear up other possibilities by ruling them out exhaustively
  however, it's more common in parsing to have exclusive choices
  so we can quickly rule out others as soon as we have one success

  without this eager shedding of disjuncts,
  other steps will accumulate in the stack

  self-shedding from the stack would require a linked-stack kind of thing

  fairness though was in mind before, with the thought that branches could easily rule themselves out
  but at the cost of unnecessary processing
  if we had fairness, there would though at least be some optionality here
  both/and instead of either/or

  the one thing we don't want is exhaustive exploration combined with unfair scheduling
  as this will save up everything as a potential backtrackable point
  
---

So we explore phases at a time
which means each time we begin a phase
we enqueue a continuation step

but, given exclusive choices, and a wide variety of concrete parselets
wouldn't each such phase be very short, and feature very few threads?

it would, but our model would at least allow disjunction by default
it would in the first place be breadth first, as it must be in order to 
limit parsing strength on concrete steps

---

the PEG wiki mentioned a big matrix of parsings
ie a cache keyed by position, but with only one result in each place

our model here is to cache only on the lhs, which means we will be duplicating parsings 
as we spread out
but differences in strength again complicate any caching scheme
also our support for multiple possibilities has the same effect:
we'd need to cache sets of results against each position of the text

---

forward parsing through the phase builds disjunctions organised by position/strength
ie our own mini-matrix covering only our next progression
but then we shed it

we need to shed options given sufficient progress on a certain leg
or parse fairly, which will allow bad legs to quickly reveal themselves
albeit at the cost of repeatedly trying bad paths ending in failure

that's the inevitable choice
and given we're attached to breadth-first in order to memoise our LHS's
as in we need to cover an entire phase each time in all of its legs till we find all the LHS steps in play
then how can we explore just one leg alone?

after finding all continuations (basically boiling down the parsing options for a position)
we're left with another disjunction
and another shared phase based on a shared (or rather, forked) Cursor

this approach basically checks each and every possibility
many of them snuffed out quickly: but they will be checked

we want the equivalent of a cut operator

---

the problem with Cut is that given our sharing of continuables via the cache
all gets munged into one
well - actually it doesn't quite, as continuations retain their original parallel separation

so, once we've parsed the LHS ParseExp
we have a disjunction that is the composite child of the previous disjunction

so in a way, we're still part of the same original choice
but the issue now is: now we have yet another disjunction
which we will naturally explore to find the next pending continuables

---

How about this?
parsing strength is static
so shouldn't it bubble up statically just like space chars?

the runtime forward-parsing of phases is itself a kind of lazy bubbling

and would it possible too to statically provide the known nested LHS of a step?
Binds certainly can do this, as there's nothing lazy about a LHS - it's just nested, readily available

so every Bind can offer up its LHS - quiet easily in fact
the OneOf receives all its steps and is able to pluck out LHS steps that are continuable
and it can also figure out the strengths required

there is potential here though for missing out given lazy follow-ons via RHS
basically it makes things a bit fragile
and the forward parsing approach just rules out all these possible gaps
plus - the potential parsing is really associated with the Cursor, not the Step,
which can include arbitrary logic
(but - why? surely all we care about here is parsing)
(so we're coming up with runtime mechanisms to cover for this arbitrariness)

LINQ commits us to this (unless we were to analyse the glue funcs involved)
but if we are committed to this...

---

so we're swimming against the tide
trying to make up for lack of static info
but we can have some static info here, with possibly some fragility
though I think this is over-egged

but what could we do with it?
it would give us forward info about what would need to be delved into
(but only need to delve lazily though we know the possibility of the subparsings)

---

the problem with the scanning up front is that it commits us to evaluate every path

does it? couldn't we scan forwards to the next concrete parsings throughout?
nothing commits us to actually exploring them
the scanning simply gets the maximum strengths of parsings
static scanning would achieve the same

but still with the possibilty of over-parsing given effective cutting

---

as we delve down into a recursive ParseExp
then subexps within it are also explored via the cache

the point is - is maximum strength even that important?
when we delve into parsing an addition, for instance
we know we can only use nested expressions within our constraints

but if we know our starting limit (as we must)
then surely that is enough
if we just used our starting strength
but applied filters on continuations
then we wouldn't need to pre-explore all paths
which would then allow us to cut out possibles

though this also explodes our previous plans...

if we know our starting strength, then we can use that to delve into continuables
but this starting strength isn't necessarily that of our current rule

in fact, it's as if the Cursor should be pre-impregnated with a strength value
that then changes as it moves forwards
but - not replaced on fork
when a rule is given a Cursor, the rule hasn't forked it
which is entirely owned by the runner
but when it moves it on, then it can set it strength

---

so the Runner forks the Cursor given a disjunction via Next
and the parsing of anything concrete gets added to the Cursor cache
(which is then released as the current leg moves forwards)

but what about recursions?
ParseExp encounters ParseExp
well really:
ParseExp(S) encounters ParseExp(S-1)

if strength is less on the recursion, then it must be a runtime error <-!!!

but this does mean we need the old mechanism of registering continuations
instead of immediately evaluating the step
we register our interest in it

we register our continuation
but we don't want to relinquish our pursuit of the current leg
but the continuations do need to be available to subsequent legs

so we return to how it was previously:
if the cell is empty then we continue our parsing
but if it has been populated, then we continue with it

but we filter results by the strength constraints of our current rule
(two kinds of strength in play then: received on the Cursor, and provided by the rule)

---

for Cut to be possible we need some way of removing steps
requiring there to be a grouping of steps at a particular disjunction
and an elimination of others in the set on the success of one
this culling could be inserted as an extra bind around each option

but for now... 
our current mechanism will produce steps on steps on steps on steps etc
which we can tolerate as long as we have a plan for sorting it

---

filtering however needs to be done

and strength needs to travel properly with the Cursor

we still want Cursor.Move and Cursor.Fork
the former will take an optional strength parameter

Steps have strength then - and we don't have to add Strength modifiers onto anything

AND STRENGTH CAN STATICALLY BUBBLE UP INTO ONEOF!
this then is a further level of strength - MaxStrength
but for now, 

---


strength then needs to propagate
but only on the LHS if a bind has a LHS with a strength then it must be the same as this
though here we have the two types of strength - the provided strength and the required strength
I'm pretending that the two are the same

ParseAdd can only be traversed by a context with a greater strength than itself
a bind containing ParseAdd must have the same constraint
but does it have the same effective strength?
possibly not: ParseAdd might be being combined with something else entirely
so strength has two parts that propagate differently
and required strength can indeed bubble
but effective strength, does this bubble?
and it's this that we _do_ want to bubble
as it would constrain our parsing of recursions

but effective strength is also a thing
ParseAdd would have an effective strength
if you put ParseAdd in a normal bind as the left, the right could still have its own strength but it would be its own business

a bracketed expression, resetting strength completely,
would have a null requisite strength, but full effective strength
but this would be on the nested expression itself
ie not on ParseBracketed, which would be part of the OneOf of ParseExp

but the inner ParseExp would still be there, with its changed effective strength
effective strength is surely a matter for within a bind
it is applied, but then reset on return
and does it get applied before processing Right?

if it is only applied to the right
then the value of the left can only be applied by the inner lefts

so effective strength is an internal matter to a bind
so it can't bubble - whereas requisite strength can

so how is effective strength to be applied within a OneOf?
the OneOf needs to know via privileged peeking
how strongly it needs to parse continuables
if effective strength is nested within the bind construct it can in fact do that

but a bind within a bind? 
we're saying effective strength doesn't apply to a left leg
yet its certainly from the left leg that OneOf needs to fish this info

a bind says do this then this
with impled control over the second bit
this also means that the bubblable props of the left leg do in fact bubble completely through binds
with no competition

so spacing is entirely determined by the left leg itself, rather than by the wrapping bind, 
which has no influence over it
where does parserinfo come from then? something has to set it
and we know returns have no interest in it

a bind with a null left instead has the chance to determine it
so at the bottom of a stack of binds, there must be either a return or a partial bind (a Root?)
every Bind on top of this then makes its parsing props avaiable

---

but Binds must also have their own params...
they shouldn't directly expose these their own params
but instead have special fields for serving via IStep

Binds then, not being completely transparent, are perhaps more like classes
closing over info

they are little machines with their own logic

---

but what about Effective Strength? well - RunSteps are of course Root Binds
and so they get to determine the overall effective strength of the bind
(with their real innards hidden within their Right leg)

more clearly separating out the roles of Left and Right legs within binds
suggests again there might be chance of having one unified strength,
in place of requisite/effective split

ie perhaps requisite strength is in left only
effective strength is clearly the strength of RightInfo
which can't be requisite, as it doesn't cover the Left
though it can be requisite on a Root 

this would make sense if RunSteps weren't themselves roots

but continuations aren't a normal case
normally, if a parsing has a strength, then it can progress as it likes
and it maintains its strength

however in consuming from a continuation
we filter what is too strong!
this is actually completely the opposite
contravariant

normally things that are stronger overrule us
in fact, they infuse us with their overriding strength
but in this case we guard against them
as we are the guards of our own little sphere
and only allow things lesser than ourselves into the inner space

in the continuation case
we form ad hoc a bind by placing a left from the continuable
alongside our known continuation

our continuation has a certain strength, and the left from the continuable has its own effective strength
it's as if the continuation bind, which is reformed with a replacement left
already has its strength decided
and we can't increase it once formed by changing its left - instead we make the whole construction impossible

the effective strength of a bind = the strength that will be enforced over its RHS
therefore, this is the strength of RightInfo

but this isn't its requisite strength, as its left is unconstrained
who knows what the left gets up to
well - we know, because the left has its own effective strength

the requisite strength of the left
is the requisite strength of the wrapping bind
but its effective strength may be different

and this requisite strength of the left
is basically the strength of the first encountered substantial step of the bind
which always is nested within the left and bubbled upwards

a Root has an equal requisite and effective strength
a Bind has two aspects, a fore and an aft
another way of putting it: a Root is unified in its strength; it can only be traversed by a Cursor
with sufficient strength to master it

but at the same time, within itself, cursors can only wield the strength that it itself expresses

ParseAdd is a bind that explicitly applies an effective strength of 50
yet this only pervades its RightInfo
it should have a left leg that is just the first ParseExp alone

but how does this differ from the normal case where a strong cursor can progress happily into a weaker step?
(but crucially a weak cursor can't go into a stronger)
the cursor that enters the left then leaves the left evidently,
but does it carry with it the strength of the left?

no it doesn't, as otherwise areas of weak parsing would bleed all over endlessly

so the strength of the left side of the bind is immaterial
apart from in how it forms a barrier
which is the requisite strength of the concoction

effective strength is an internal matter
only peeked at magically by OneOf

the strong cursor that enters the bind
must get past the left leg
but once past that, it returns to its original incoming strength
and traverses the right

the issue here is that 
with the continuation mechanism
a preexisting bind is taken
with an existing strength to its left leg
and replaced with an element of filtering
but there is no necessity to this filtering
as the strength of the left leg has no bearing on anything else, apparently

yet the bind doesn't just do one and then the other - it sequences
the cleanliness of the left is because it cleans up after itself
a bind resets changes to strength on its completion

however in the original case here,
does the weakness of the left bleed into ie affect the further steps of the rule?
if so this would necessitate our filtering of the cuckoo left leg

but there is an implied expectation 
that the left is constrained to a certain strength
our matter isn't fitting a cursor into our composite bind
but in replacing like for like among the steps
/we are committed to keeping true to our constraint/

---

the continuable can /and maybe should also/ remain in the right of the RunStep Root
the strength of the RunStep closes over it
and declares that is has a certain strength
meanwhile OneOf can peek into the effective strength and tot up its practical maximum
and our task is simply to supply emissions within the requisite strength

that is the meaning of the expressed constraint: that nothing stronger than the stated limit sit there
and we can abide by that

it does mean though that were a Bind be in the OneOf, its LHS would be ignored
yet it shouldn't be! the magic of the Root RunStep is that /it has no left, and therefore propertes of the right take its place/
with a normal Bind, the left is more important to the OneOf

so, the OneOf should be sensitive to the lefts of its members, or to the rights if roots
does this mean that /it is in fact the Info, not the RightInfo that should be aggregated?/
YES!

---

but does the OneOf even need to be sensitive to anything?
the cursor will always have its current strength
which limits the parsing reasonably already

it would help in some cases, though certainly not common or expected ones

so, for now maybe this can be sidelined as a potential optimisation

---

still though, although we discover and cache continuables inline,
and we've decided we can ignore aggregating their maximum strengths up front

we need to execute them with the leading effective strength, not that of the rule

we covered this above, with Cursor.Move() optionally changing the strength of the cursor

so, the bind itself only applies its known strength on moving the cursor?
this seems arbitrary tbh

we need to maintina two strengths instead
normal strength and also an 'outer strength'
which is the effective strength of the nearest enclosing OneOf
though this would be optional, as it will only be available on the first parsings of a rule

and these should live as now in the Cursor
so as the Cursor is Forked, there should be opportunity to set the outer strength as a momentary override
that gets cleared with the continuation dictionary

or even - maybe the dictionary itself needs to be paired with an effective strength at the point of construction

---

to further recap

the strength of the continuation dictionary gets assigned
before it is forked

then the strength of the cursor is changed,but before it moves forwards

---

on the continuation, we just receive a cursor and a step
this is what we need to filter out

the step is just a return
does this really have a strength?
the cursor obviously does have a strength

but this cursor is supposed to be reset
the emission of results must then be done before it is reset!








* Tasks
** TODO continuations to filter on incoming strength
** TODO strength to bubble up through Bind lefts
** DONE Continuations to live inside Cursor
which means adopting Cursor.Move and Cursor.Fork
** DONE make binds propagate ParserInfo from Left, unless Left is null
need special fields for themselves, alongside special props via IStep for above consumption
** DONE strength to be part of ParserInfo
** DONE strength to bubble up into OneOf for limiting of parsings
* Scratch


